GSTLoadoutsDb = {
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Catgirlhunt-stormrage",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0zADsMGNWGQmtYDAAAAAAAAAAAAAgZMjZYmhZ0MjxwYYWmxMLzgtZmx2MLz22MGzgZmxYmZWMGsM",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Firebuttmeh-illidan",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jDYbWMmxMmFDzMzw0YmxAAAAAAgBCYmZaZWWmBAymxMYMzYmxsYWGzYmhZ2mhZWwAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 1,
    ["name"] = "Iaintblack-frostmourne",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAAYxyMLjZxsNmZshNbzGzGz2yyMzyCDNzMDMDzAYbmZGmNmZYWmJAAAAAz202sNzysZZ2WmtZmJIAwGA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Clanhack-azralon",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAzAAAAYZMzMzMmZWMjZxMsMMGbbz0SMzyMmZGGY2yAAGYgNgNmFzYmlZbmZWaAAABsAA2YMmhB",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Tyraene-illidan",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAGAAgBYZMzMzMmZWMjZxMsMMGbbz0WMjZMzMMwslBAMwAbAbMLmZmZZ2mZmlGAwMzy2SLzMsAYwCDMmB",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Ishikk-tichondrius",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsZMYWGLzMjZmZZbmZGzsNGGAAgBAAAAAAg2amZWMMzwYwWbAwYgBwAbDAAwMTLzysNDQgNGMAMYGGD",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Heartfels-jubeithos",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbgZmZmZmZEzmBmNzMDz2AAAAmZMzyMjxyMzMLmxMDAYGLwAziRjZAZWCWmBAAAAAAAAzwCA",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Dumbfatbald-black-dragonflight",
    ["code"] = "CsQAYIOwXTfhprvln24ZeRPDbMMmxMMjmZ2MjxsMjZY2mNjxMmFz2MLLzMDAAAAgZ2WmZWGWgBmFjGzAysFbYAAAAAAAMjxMAA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 3,
    ["name"] = "Bigdwagon-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAmZmZ2mlBGzMjZxMzYAAAwMjZmZMGmJmZGAAAwMzMNDzMGzMAgxYMbWYxCDzMz0QzCjFDD",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Dubai-demon-soul",
    ["code"] = "CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzYMmZMmJDzAAAAAAAmFjZbmZmZmtZmZbWmtxwMDzYbbWmZZWmZmZbbWmmmhZmBsA",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Trtherapy-illidan",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAmZMMjhZkZmhZYmZbmhhtZMzMMjBz2MzsZmZbmhZAAAAY2mZZWmZmZZbWmmmBzMMWA",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Diuoe-demon-soul",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALjys0MGzMAzmZZmZ2GwwsMzyMWmZGmZWMLzMmZGbADwYbZmlltZWmtZamZZmCAABwCGjB2MMG",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Øneêyêdøwl-twisting-nether",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlMGzMwDYWGLzMDwMGLzsNjFmZmZmlZMzYmZshFGgBYbbsgpZmlRBAgAYzMzMAbGYA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Åëöñíç-moon-guard",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlmxYmBY2GLzMzGDmFzyMLzYbmZGzMLmlxwMshFGgxy2MbbbzsNLz0MzyMFAACgFzMGDsZgB",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Franksinatrà-sargeras",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAgxMbziZ2YGzMbzGjlZmZ8AzMAAAAAALBzmBmZmaGzmZZmZ2GGGAAAAAAAMAAgA0MLz2Mz2Mbzs0sNzyGMmBwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Twwferal-tichondrius",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZb2YsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GzwAAAAAAAgBAAEgAgZbmlmtZW2gxAwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Abstractf-sargeras",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZb2YsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GzwAAAAAAAgBAAEgAgZZmlmtZW2gxMAWYwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Motivate-andorhal",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAgxMbziZ2YGzMbzGjlZmZ8AzMAAAAAALBzmBmZmaGzmZZmZ2GGGAAAAAAAMAAgAEAMLzs0sNzyGMmBwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Concept-andorhal",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZb2YsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GGGAAAAAAAMAAgAEAMLzs0sNzyGMmBwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Tråppin-sargeras",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmtlxwYbMTjlZWYLzWmNAAAAAAAAAAAAAAmhxMjZMmRzMzMzYmhxMYZglBzyMbDzMzMmlZmhxMzsZMGLD",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Jésús-dalaran",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmtZZ0stMMjmZpBLzMz2MzMzYGjhZGmxYmZmNAAAAAAAoZMjZYmZmBGzMDzMMmZMbDsAAAAAAMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Solver-shandris",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmlZb0stMMjmZpBLzMzyMzMzYGMzMGmxYmZmNAAAAAAAoZgZGzMzMwYmZm5BmhxMjZbgFAAAAAgBA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Numbing-sargeras",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMzCDzYGjpxYMAAAAAAGIgZmplZZbmZmllltZmYDAAAAAgNAMGmZWmlxMMmZGzMzMzMmxYA",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Còwabunga-bleeding-hollow",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYbmNLzMzMmZWGwMzYaMGMAAAAAAmZZmmZWmlZmplZZZGAILGzgZMmxMzmZbMmZwMbDLsMmZAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Cittyg-tichondrius",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmtZZmZmxMziBGzYaMGMAAAAAAmZZmmZWmFIAAILGzghxMmZ2MbjZmZwMbzYhlhZAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Êårth-area-52",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwyywImZmtxMbAw2MegZMbzCzYWmJAAWGzMMDz2MQAssMLLzyMz0sNLNzMzCMA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Humidifierxo-moon-guard",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAADLWmZZYjtxMjFDbbzmZYbWW2mZswMamxADzMYYWmZmhZxyAzyMBAAAAYWm2mtZWmNLz22sNzMBBAWA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Manongauz-demon-soul",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAADAAgBYZMzMmZbmZxMmNzw2AmttZarxMLGmZYAbZAADA2A2YWmZMzysNzMLNAgZmltlWmZYDAsZGmZ2MD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Highnèss-kelthuzad",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsZMYWGLzMjZmZZbmZGzsMGGAAgBAAAAAAg2amZMDzMMGs1GAMGAgZw2AAAMz02sMbzAEYjBDADmhxA",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Frumples-emerald-dream",
    ["code"] = "CYEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAassMzstsNzYZmZ22MbAAAAAAYWaamFDzw2MY2GmlZbGwwMMDLLsBAmtZbmZWaQAAALADAGjZMG",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Woollyp-frostmourne",
    ["code"] = "CYEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAassMzstsNzYZmx2mZDAAAAAAzWTzsYYmx2MG2GmlZZGwwMMDLLsBAmlZbmZWamZabWmtZAALADAmZMjB",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Adhd-dalaran",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAGmxsMzMzMDzwwMLzMzMAAAAwsNbzGjZmBwsYMYYW2sYmZmaAgZWmZZbbysNzsMgmZbwixwA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Copperjohn-chogall",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfDDzAAAAAAAAAAAAgxMLmZbmxysMzMzMzyYmtBzGzMzwsxsgxMDWWGqZGsBjZGMzilpmNDmlZZJjZ2YDA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Bestrussian-area-52",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfDDzAAAAAAAAAAAAgxMLmZbmxysMzMzMzyYmtBzGzMzwsxswMGDWWGqZGsBjZGMzitpmNDmtZZJjZ2YDA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Jw-malorne",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYmHYMzMmZAAAAAAAz2MmtZAAAAAAollhZYmxYmZWGDmZMzMzMzYGW22GDGsNz2YjxMmlGz22wkthhlB",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Jax-tichondrius",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0YG8AzwYMmZmZmxMmtxMGLLDzwMjxYmlxAAAAwMMDLmlZMbzwYhhlZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Askbotanical-sargeras",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMzyMDD2mZMPwMz2MzyyAAAAAAAAAAAsgllZMzssoZZbYGNz0gNAMbTmhxmxYmBzMzGWmx0stwMbjZGAgBA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Chillatech-tichondrius",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYmZmxMbjBz2ysMzyMsYZZmFLMmx20YZmFmMTGLMPwYzyMbMGNzyyYmpZMDDsYMzsZ2mZb2YAAgB",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Nesq-tichondrius",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbAzMzMzMjGz2gxsxMDzyAAAAmZMzyY4BWegZmZxMzMDAYmZZZZMMmFz0YmZYLzSG2mBAAAAAAAAMz2A",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Voidlockese-emerald-dream",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbwYmZmZmZEz2gxsxMjZWGAAAwMjZWGDPwiZmZxMzMDAwMLLLDMwMhZG2yIDbzAAAAAAAAgxMbD",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Menudoytacos-sargeras",
    ["code"] = "CoQAYIOwXTfhprvln24ZeRPDbwDwMzMzMjGzygxsxMjZWGAAAAAAAAAAmxyyMmZGWMZYmlZrNaGbMjZGbjZ2MzMzMzMjZYGzMDYGAAA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Magnuszx-zuljin",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGzMjZMPwsNLLLzMAAAAYGmmxYMzMbMGjBmZwwMjZAAAAAAAYmZWGjBQMjltZxMbDbGGmZmpFamBb",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Tractordaddy-zuljin",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGzMjZMPwsNLLLzMAAAAYGmmxYMzMbMGjBmZwwMjZAAAAAAAYmZWGjBQMjltZxMbDbGGmZmpFamBb",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Warriörgöd-moon-guard",
    ["code"] = "CgEAO9DBjZzKcjSu6RJDto0RCCAAAAAAAAAjGDzMbMDGzwYjZmZMMzYmZbbMzMzsxMDjZmZYZYmhZGAAAImZZbsxmtFz0YmZYysxMsB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Sailw-thrall",
    ["code"] = "CkEAO9DBjZzKcjSu6RJDto0RCKGAAAAmZmZMzMMz2MLzMzsBgYMGgBAMAAAAAAAAYmBAYZbDAAAEAgAA",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Sleepiihead-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAGzMz2sMwYmZeAmZmxAGAAMzwMzYMMTYmBAAAMzMTzgZmZbMAAYMb2YBGYGN0wMWgB",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Sicklikeme-zangarmarsh",
    ["code"] = "CEcBV7//nP39x/JJympTqouKSwMLjtZmZGbGzMjZYmZGAAAAAgZAAwMzwMjxQNMzMAAAAYmZshZ2mZMwMGGmlZz2ysMMz2wMMz0I2gZA",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Happywhale-tichondrius",
    ["code"] = "CoPAtbMOTHlnKIwUyAn+DK70SjhZmZGYMjZsMzMmZaGmxYMjZAAAAAYGzMjxMz2MjxAAAMmZmZGAAAgZ22GDjZMbNW2WGmsNMsMAzwA",
    ["classId"] = 6,
    ["specId"] = 250,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Tygasoraw-tichondrius",
    ["code"] = "CwPAtbMOTHlnKIwUyAn+DK70SDgZmBjZMjlxMmZmGGGzMjZAAAAAAAAAwMjZMGzMAwwMMbzYmZmxMzYw2MbmZmRzsswsxsNNWYAMDA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Bound-blackrock",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAmZMmZMMjMzMMDzMbjxMsNDzMmZMY2mZmNzMmZYGAAAAmtZwwYZhJZwMDjF",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Rfc-tichondrius",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlmxYmBY2GLzMzCDGmlZWmxyYmxMzixYmZmxGWAwgZ222GbjZamZZUAAIA2MGjB2MmxA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Scuffedx-tichondrius",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzMjxMWmZMMjZGLeghZsMLDYxMGNRzY2MLzMzyYGGAAAAAAGMDAAgAqZWmlZmtBEgFYAYxMDD",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Mopdruid-uther",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzYMMzyMMjZMzYhZmxsMLDMbmxoJyMz2MLzMz2YGAAAAAAwwYALLzshxsMCMFAACwGMAssMwA",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Metaphorest-kelthuzad",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtZmZmtNjZmxmZZYYssx2ilZAAAAAAAAAAAAsMDZjx0MzMwsZWmZsYMMAAAAAwAGAALbjFMNzsNEAMLzs0sNziNGzYwMDQD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Samuelceo-area-52",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtZmZmtNDzM2MLDDjlN2WsMDAAAAAAAAAAAglZILMmmZmBmtZWmZmFMMAAAAAwAAYALLjFMNzsMEAMbzs0sNziNGzYwMDQD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Bluedru-tichondrius",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtZmZmtNjZmxmZZYYssx2ilZAAAAAAAAAAAAsMDZjx0MzMwsZWmZsYMMAAAAAwAGAALbjFMNzsNEAMLzs0sNziNGzYwMDQD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Yoske-tichondrius",
    ["code"] = "C0PAIKKe/J2LdooRW3uJg8yy0bstNjZmhNTWYWmZrhmxGAAAAAAGDbDzyMzMMzwMzsMmxMDmxMZGDzMzMGzMMmZmxMDjZw2ALAAAAAAAA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Robotwo-illidan",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmtlxwYbMTjlZWYLzSmFAAAAAAAAAAAAAAmBmZMjZmRmZmZGPwMMLzMsNwygZZmtx2MzMjZZmZYMzYbZMYZA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Jésús-dalaran",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmtZZ0stMMjmZpBLzMz2MzMzYGjhZGmxYmZmNAAAAAAAoZMjZYmZmBGzMDzMMmZMbDsAAAAAAMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Junglejape-tichondrius",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMzGYmZYMNGjBAAAAAwABMzMtMLbzMzssssNzEbAAAAAAsBgxwMzysMmhxMzYmZmZmxMGD",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Boømbam-bleeding-hollow",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMziBmZGTjxgBAAAAAwMLz0MzysMzMtMLLzAAZxYGMMmxMzmZbMzMDmZbGLYMzAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Polarpop-malganis",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmNLzMzMmZWGwYGTjZGMAAAAAAmZZmmZWmlZmplZbbGAILGzghxMzMzmZbMzYwMbzYBjZGAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Fraudcheck-tichondrius",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwyywImZmtxMbAw2MmZMbWYGzyMBAwyYmhZY2mBCgllZZZWmZmmtZpZmZWgBA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Goongob-tichondrius",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwyywImZmtxMbAw2MmZMbWYGzyMBAwyYmhZY2mBCgltZZZWmZmgAgBA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Halfstomp-tichondrius",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwy2wImZmNmZDgx2MmZMbWYGzyMBAwyYmhZY2mBCgltZZZWmZmgAgBA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Nahzbal-area-52",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAADAAgBYZYmxMbzMMzMLmxDsNgZbz0SjZWMMzwA2yAAGAsBsxsMzYmlZZmZWaAAzMLbLtMzwGGwYxMMzwMA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Michaelsmith-frostmourne",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsNj5BMzyYZMzMjx2MzMzMYYAAAGAAAAAAASmZWMMDGzMzWbAwYAAmBbDAAwMTbzysNDQgNDMAMzwwYA",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Mybackhurts-sargeras",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAMmZmlxMjZYGGmZZmZmBAAAAsNbzygZmBwsMjhZY2YxMzM1AAzsNz222kZbmZbANzygFjhB",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Jax-tichondrius",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0YG8AzwYMmZmZmxMmtxMGLLDzwMjxYmlxAAAAwMMDLmlZMbzwYhhlZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Dàzèd-stormrage",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0MzgHYGGDmZmZmZmxsNMmZZZMDmZMGzsMGAAAAmBDbmlZMbzwYhhlZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Wavedodger-tichondrius",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2gBMBzGTIzCAYMNzwMbGjpBzMDsMjZmNz2MbzGzMDMzsBA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Roar-tichondrius",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2gBMBzGTIzCAYMNzwMbGjpxYmZglZMzsZMz2sxMzAzMbA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Askminx-sargeras",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMzyMDPA2mZMzMz2MzyyAAAAAAAAAAAsgllZMzssoZZbYGNz0gNAMbTmhx22YMzMMzMbYxYa2WYmtxYAAGA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Askronnie-sargeras",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMzyMDD2mZMPwMz2MzyyAAAAAAAAAAAsgllZMzssoZZbYGNz0gNAMbTmhx22YMzMMzMwyMmmtFmZbYGAgBA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Kaskä-tichondrius",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMMz2ysMWmhFbLzsYjxM2mGbzsxkZyYh5BmhlZMzYmmxyYmpxMDDsYMzsZ2GbzGDAAM",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Angryreubenx-sargeras",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMYWWmlZWmhNbmZBGwEMbMhMWYmxmlZ2YMTzstMmZaMzwAMmZ2MbzsNbMAAwA",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Langneur-medivh",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbMMzMmZmhmZ2AmNmZMzyAAAAmZMz2Y4BWMzMLmZmZAAzMLLLjhxsYmGzMDbZWyw2MAAAAAAAAYMz2A",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Rosemarý-area-52",
    ["code"] = "CsQAYIOwXTfhprvln24ZeRPDbwDwMzMzMjY2GWGzGzMmZZMjZmZmlZ2YbxMDAAAAMzMsMzsMshZmxMLLjmZG2GtMbN2wAAAAAAAYYGDAA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Smaxxin-tichondrius",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGmZMjZmtZZZZMAAAAYGmmxYMmZhZbwM2MzghxYGAAAAAAAmZmlxYAWiZssNLmZbYzwwMzMtQzMYB",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Rennarwar-illidan",
    ["code"] = "CgEAO9DBjZzKcjSu6RJDto0RCCAAAAAAAAAjGzYMMzssY2GwCzMGDzMmZ22GzMzMLwYGzMzMWGmZYmBAAAixy2AbgJYGmAzwG",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Truffleßutta-tichondrius",
    ["code"] = "CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAAGzMYmNzYmBzYGDTDzMZ2GLzMzMjZMzyMgZmZ2YmZbMDMwYwGsMGN2GQmJAbYA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Stælthßømbèr-baelgun",
    ["code"] = "CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAAGzMYmNzYmBzYGDTDzMZ2GLzMzMjZMzyMgZmZ2YmZbMDMwYwGsMGN2GQmJAbYA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Sleepiiheadx-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAGzMz2sMwwMzwMzMGwAAgZGmZGjhZCzMAAAgZmZaGMzMbjBAAjZzGLwAzohGmxCMA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Myayongc-tichondrius",
    ["code"] = "CEcBV7//nP39x/JJympTqouKSgZZsNzMzYbGzMjhZmZmZDAAAAAGAAYmBzwYomxMzAAAAAzMzGzMbjZAGzYYWmNbLzywMbDzwMTjYDjB",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
};
