GSTLoadoutsDb = {
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Aerythea-frostmourne",
    ["code"] = "CoPAtbMOTHlnKIwUyAn+DK70SjxYMzYMjZmZYMjZmmhhZmZGDAAAAAMzMzMzMzsxMDAAAzMzMzMAAAAzssNGGzYWasstMMZbYYDgZMA",
    ["classId"] = 6,
    ["specId"] = 250,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Mograinedk-area-52",
    ["code"] = "CwPAtbMOTHlnKIwUyAn+DK70SDgZGjZMGDzMzMzMNMjZGzYAAAAAAAAAgZYmZMzMDAMbmhZZYmZmHYmxYwyMLmZmRzssxsxsNN2AgZA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 3,
    ["name"] = "Entrid-stormrage",
    ["code"] = "CEkAEDLOxe3SEPP2R8Hw6bhoSYmZmZmZGjZmZMMNDzAAAAAAAmFjxMjZmZbMzGWmZwYYssNLzghx2GTyMmZGGWA",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Kittysuno-frostmourne",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmtmxYmBYWYZmZWYYmFzyMLzMbzMzMzMLmlxwgNsAgxy2MbYMbjATBAgAYxMjBYzwYA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Austin-icecrown",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZbWYsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GzwAAAAAAADMAAgAEAMbzs0sNzyGMGAWYwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Kirarrgi-ragnaros",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAzMbzmZWYmZmZzmZsNzMzYmBAAAAAYJY2MwMjaGzyYZmZWGzYGAAAAAAAAAAEgmZZWmZ2GQgFYmBgFGM",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 1,
    ["name"] = "Dorkibear-sargeras",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzYmhZWmZMjZMzYhZGmFLDYzwoJyMzyMbzMzyYGDAAAAAAGGDYZbmNMmtRgpmZZWmZ2GQA2MmBgNDM",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Vegansquishh-area-52",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzYmhZWmZMjZMzYhZGmFLDMbGGNRmZWGbzMzyYGDAAAAAAGGDYZbmNMmtRgpAAQA2MmBgFDM",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Diashifty-malganis",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtxMzYjZmZmFz2MDYZhtlZbGAAAAAAAAAAAALDa2MMNDzYMLsMzwMmZGAAAAAAAAgtlxCmmZWGCAmtZ2aWmZzGjZgZMLgG",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 1,
    ["name"] = "Véz-frostmourne",
    ["code"] = "C0PAIKKe/J2LdooRW3uJg8yy0DMmxwCZDmRDNsBAAAAAgxY2m5BsMzMwMjZYxMjZGjZGTmxMmxMDzMjZYMmxwsMDWmBbAAAAAAAA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Catgirlhunt-stormrage",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0zADsMGNWGQmtYDAAAAAAAAAAAAAgZMjZYmhZ0MjxwYYWmxMLzgtZmx2MLz22MGzgZmxYmZWMGsM",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Agravaine-barthilas",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmttxwYZMTjlZWYLzWmNAAAAAAAAAAAAAAmhxMzMzMmRmZGjZMwwMbzgtZmx2MLz22MGzgZmxYmZWMGsM",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 1,
    ["name"] = "Xyroblast-malganis",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jDYbWMmxMmFDzMzw0YMmBAAAAAgBCYmZaZWWmBAymxMYMzYmxsY2GzYmhZ2mhZWwAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Firebuttmeh-illidan",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jDYbWMmxMmFDzMzw0YmxAAAAAAgBCYmZaZWWmBAymxMYMzYmxsYWGzYmhZ2mhZWwAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 1,
    ["name"] = "Iaintblack-frostmourne",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAAYxyMLjZxsNmZshNbzGzGz2yyMzyCDNzMDMDzAYbmZGmNmZYWmJAAAAAz202sNzysZZ2WmtZmJIAwGA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Impaak-thrall",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAAjZhZgNMjZmlHgNbz2MzmtZZbbmZZhZ0MzMwMMDGsMzMDz2YMYxEAAAAAEgFLzyysNzMBBAWA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Clanhack-azralon",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAzAAAAYZMzMzMmZWMjZxMsMMGbbz0SMzyMmZGGY2yAAGYgNgNmFzYmlZbmZWaAAABsAA2YMmhB",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Tyraene-illidan",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAGAAgBYZMzMzMmZWMjZxMsMMGbbz0WMjZMzMMwslBAMwAbAbMLmZmZZ2mZmlGAwMzy2SLzMsAYwCDMmB",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Ishikk-tichondrius",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsZMYWGLzMjZmZZbmZGzsNGGAAgBAAAAAAg2amZWMMzwYwWbAwYgBwAbDAAwMTLzysNDQgNGMAMYGGD",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Cyndylou-hyjal",
    ["code"] = "CAQAmmmbZv0rzNjRHT4p8IjZfDA2mxMGjxYGMz2MbzMzYmZGAAAAAAAAAAwysMbMmZGMLMmxgBLegtZampxiBmZmZBLUMmlZWmtNjNjFbA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Sperclezz-frostmourne",
    ["code"] = "CAQAmmmbZv0rzNjRHT4p8IjZfDA2GmxMzMGzMMzmZbmZmZGzAAAAAAAAAAAzilZbwMzgZhhhZMMLbDTjJWGAmZBLUMmtBYshFAA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Ligases-tichondrius",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAwMzsMmZmZYGGmZZmZmBAAAAmNbzGMzMAmFjxYMz2mFzMzUzCAmZDbEGzyAasBLGDD",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 1,
    ["name"] = "Improvement-tichondrius",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfPgZGAAAAAAAAAAAAMmZxwMzsYbmZmxsNPwMbDmNmZmhZjZBjxwsY2mamBLwYmBAFgZb22CmNWAA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Richx-illidan",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMwYGzYwMzwMMMzMzMjZmplZMLzAAAAAAgttZmBzMjlxMLz2AAAAwMDwgZb2MzMjmZ2YWYZbahFzA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Booger-malganis",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMDMzDMDzMz8AzMLzMYZAAAAAAAAAA2AsZGDbkFYGN0gFAMbTGYWMDDGzMz2wyMz0swyMLjZGAgxA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 2,
    ["name"] = "Heartfels-jubeithos",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbgZmZmZmZEzmBmNzMDz2AAAAmZMzyMjxyMzMLmxMDAYGLwAziRjZAZWCWmBAAAAAAAAzwCA",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Láo-bleeding-hollow",
    ["code"] = "CoQAYIOwXTfhprvln24ZeRPDbgxMzMzMjY2MMmNzMDzyAAAAAAAAAAYeAwYGDLkBWGtQDLMzYmZbMzmZmZmxYmZwYmZMYGAAA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 3,
    ["name"] = "Grimdots-sargeras",
    ["code"] = "CsQAYIOwXTfhprvln24ZeRPDbAmZmZmZEzmhxsZmZY2mNjxMmFzmZZZmZAAAAghZ2WmZWmxCMwsY0YGQmtYDDAAAAAAgZMmBA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Dumbfatbald-black-dragonflight",
    ["code"] = "CsQAYIOwXTfhprvln24ZeRPDbMMmxMMjmZ2MjxsMjZY2mNjxMmFz2MLLzMDAAAAgZ2WmZWGWgBmFjGzAysFbYAAAAAAAMjxMAA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Afreecalion-area-52",
    ["code"] = "CgEAO9DBjZzKcjSu6RJDto0RCCAAAAAAAAAjGzYMMzsxsNYswMjxwMjZmttxMzMzygxMmZmZsMMzgZAAAgYssNwGYCmhJwMsB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 3,
    ["name"] = "Jingzhe-kiljaeden",
    ["code"] = "CkEAO9DBjZzKcjSu6RJDto0RCKGAAAAmZmZMzMmZWmZZmZmNMGjGzyYGmZhZmhlZmxMwwAAAAAAAGDAYZbDAYzMGWIDMDL0wsA",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Bloodymural-area-52",
    ["code"] = "CkEAO9DBjZzKcjSu6RJDto0RCKGAAAAmZmxMzMGzyMLmZmNMGjYWGzwYZMzMsMzMmBGGAAAAAAYmZAALbLAAbmxwGZgZYhGzsA",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 3,
    ["name"] = "Bigdwagon-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAmZmZ2mlBGzMjZxMzYAAAwMjZmZMGmJmZGAAAwMzMNDzMGzMAgxYMbWYxCDzMz0QzCjFDD",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 5,
    ["name"] = "Bongzillatv-area-52",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAGzMz2sMwYmZeAmZmxAGAAMzwMzYMMTYmBAAAMzMTzgZmZbMAAYMb2YBGYGN0wMWgB",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "pve",
    ["rank"] = 4,
    ["name"] = "Dragonzombie-barthilas",
    ["code"] = "CEcBV7//nP39x/JJympTqouKSwMmZbMzMMYmxMzMzYmNAAAAAwAAgZGAjxUDzMDAAAAmxMbjZmlxMDMjZMYBWGDjtBwMRshZG",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Akkaz-korgath",
    ["code"] = "CsPAtbMOTHlnKIwUyAn+DK70SPAMzYgZMjtxMmZmZYYmMjZMYwMMzMmZmZmZmlZGAAAAAAAAAAAgxy2sZ2mhxCDLzsNN0M2MmZYmZA",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Dubai-demon-soul",
    ["code"] = "CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzYMmZMmJDzAAAAAAAmFjZbmZmZmtZmZbWmtxwMDzYbbWmZZWmZmZbbWmmmhZmBsA",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Trtherapy-illidan",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAmZMMjhZkZmhZYmZbmhhtZMzMMjBz2MzsZmZbmhZAAAAY2mZZWmZmZZbWmmmBzMMWA",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Thè-argent-dawn",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAmZMmZMMjMzMMDzMbjxMsNDzMmZMY2mZmFzMmZYGAAAAmtZwwYbhJZwMDjF",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Felwéávér-tichondrius",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAGjxMMzMzkZmxYWmZmlZGzM2GmxYYGMbzMzyDMGzMmZAAAAY2mZZWmZmZZZWmmmBzMwC",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Diuoe-demon-soul",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALjys0MGzMAzmZZmZ2GwwsMzyMWmZGmZWMLzMmZGbADwYbZmlltZWmtZamZZmCAABwCGjB2MMG",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Øneêyêdøwl-twisting-nether",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlMGzMwDYWGLzMDwMGLzsNjFmZmZmlZMzYmZshFGgBYbbsgpZmlRBAgAYzMzMAbGYA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Pløki-tichondrius",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALjys0MGzMAz2MLzMzGDGmlZWmZWGPwMzYWMLzMjZMbAAGgltxGmmZ2GFAACgNjxYgNDM",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Åëöñíç-moon-guard",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlmxYmBY2GLzMzGDmFzyMLzYbmZGzMLmlxwMshFGgxy2MbbbzsNLz0MzyMFAACgFzMGDsZgB",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Franksinatrà-sargeras",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAgxMbziZ2YGzMbzGjlZmZ8AzMAAAAAALBzmBmZmaGzmZZmZ2GGGAAAAAAAMAAgA0MLz2Mz2Mbzs0sNzyGMmBwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Twwferal-tichondrius",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZb2YsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GzwAAAAAAAgBAAEgAgZbmlmtZW2gxAwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Abstractf-sargeras",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZb2YsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GzwAAAAAAAgBAAEgAgZZmlmtZW2gxMAWYwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Motivate-andorhal",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAgxMbziZ2YGzMbzGjlZmZ8AzMAAAAAALBzmBmZmaGzmZZmZ2GGGAAAAAAAMAAgAEAMLzs0sNzyGMmBwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Concept-andorhal",
    ["code"] = "CcGAkuH5GdQpDrgY32rlVGnyqBAAAAAAmZbWMzGzYmZb2YsMzMz8AzMAAAAAALBzmBmZmaGzmZZmZ2GGGAAAAAAAMAAgAEAMLzs0sNzyGMmBwCzwA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Munkiki-ragnaros",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzMzMjxyMz2YmZmBwwsYBMbzMGNRmZ2GLzMzCzAAAAAAYAMDYZbmNMmlRgpmZZWmZ2GQA2YMAsZMM",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Huntations-sargeras",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmtlxwYZMTjlZWYLzSmFAAAAAAAAAAAAAAmBmZMjZmRmZmZGzMMmZYbglBzyMbjlZmZGzyMzwYmx2yYwyA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Tråppin-sargeras",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmtlxwYbMTjlZWYLzWmNAAAAAAAAAAAAAAmhxMjZMmRzMzMzYmhxMYZglBzyMbDzMzMmlZmhxMzsZMGLD",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Jésús-dalaran",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmtZZ0stMMjmZpBLzMz2MzMzYGjhZGmxYmZmNAAAAAAAoZMjZYmZmBGzMDzMMmZMbDsAAAAAAMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Solver-shandris",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmlZb0stMMjmZpBLzMzyMzMzYGMzMGmxYmZmNAAAAAAAoZgZGzMzMwYmZm5BmhxMjZbgFAAAAAgBA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Jimmyjobs-zuljin",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmlZb0ssMMjmZpBLzMzyMzMzYGMzMGmxYmZmNAAAAAAAoZMMjZmZmBGzMDzMMmZMbDsAAAAAAMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Yahwéh-area-52",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmtZZ0stMMjmZpBLzMzyMzMzYGjZMGmxYmZmNAAAAAAAoZYMDzMzMwYmZGzMMmZMbDsAAAAAAMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Numbing-sargeras",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMzCDzYGjpxYMAAAAAAGIgZmplZZbmZmllltZmYDAAAAAgNAMGmZWmlxMMmZGzMzMzMmxYA",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Kalvásflam-stormrage",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmZmZWAzYYMNGjBAAAAAwABMzMtMLLzMzssssNzEbAAAAAAsAgxwMzysMmhxMzYmZmZmxMGD",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Stëpsister-illidan",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzMzMmZ2APw8AzYMNGjBAAAAAwABMzMtMLbzMzssssNzEbAAAAAAsBgxwMzysMmhxMzYmZmZmxMGD",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Ichìmaru-stormrage",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMzGYGzYMNPwYMAAAAAAGIgZmplZZbmZmllltZmYDAAAAAgNAMGmZWmlxMMmZGzMzMzMmxYA",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Spectretribe-tichondrius",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYbsZZmZmZmZ2gxMDTjxAAAAAAAmZZmmZWmlZmplZZZGAILGzghZmx8AzmZbMzMDmZbYhlxMDAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Poofrombutt-demon-soul",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmtZZmZmxMWmBGzYaMGMAAAAAAmZZmmZWmlZmplZbbGAILGzghxMzMzmZbMzYwMbzYhlhZAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Còwabunga-bleeding-hollow",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYbmNLzMzMmZWGwMzYaMGMAAAAAAmZZmmZWmlZmplZZZGAILGzgZMmxMzmZbMmZwMbDLsMmZAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Cittyg-tichondrius",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmtZZmZmxMziBGzYaMGMAAAAAAmZZmmZWmFIAAILGzghxMmZ2MbjZmZwMbzYhlhZAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Êårth-area-52",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwyywImZmtxMbAw2MegZMbzCzYWmJAAWGzMMDz2MQAssMLLzyMz0sNLNzMzCMA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Humidifierxo-moon-guard",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAADLWmZZYjtxMjFDbbzmZYbWW2mZswMamxADzMYYWmZmhZxyAzyMBAAAAYWm2mtZWmNLz22sNzMBBAWA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Manongauz-demon-soul",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAADAAgBYZMzMmZbmZxMmNzw2AmttZarxMLGmZYAbZAADA2A2YWmZMzysNzMLNAgZmltlWmZYDAsZGmZ2MD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Cloudx-shattered-hand",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsYmxYWmZZmZmZM2MmZMLMMAAADAAAAAAAt1MzsYYmZMMjtWAAGAgZw2AAAMz02sMbzMzsst02MjFgBgZYGDD",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Highnèss-kelthuzad",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsZMYWGLzMjZmZZbmZGzsMGGAAgBAAAAAAg2amZMDzMMGs1GAMGAgZw2AAAMz02sMbzAEYjBDADmhxA",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Frumples-emerald-dream",
    ["code"] = "CYEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAassMzstsNzYZmZ22MbAAAAAAYWaamFDzw2MY2GmlZbGwwMMDLLsBAmtZbmZWaQAAALADAGjZMG",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Woollyp-frostmourne",
    ["code"] = "CYEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAassMzstsNzYZmx2mZDAAAAAAzWTzsYYmx2MG2GmlZZGwwMMDLLsBAmlZbmZWamZabWmtZAALADAmZMjB",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Vindicted-zuljin",
    ["code"] = "CYEAN/WrsXv0CO5mzTm8Icl8KAAAAYAAillZmtltZGLzM22MLAAAAAAYWaamFDzMWmxY2GmlZZGeAGmhZYZhFAwsNbzMzSzMTbzysNDAYBAMwYMDzA",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Mypriest-shattered-hand",
    ["code"] = "CAQAmmmbZv0rzNjRHT4p8IjZfDDw2MzMeAjZYGY2mxMzMzYmBAAAAAAAAAAmtZZWYMzMAmlZmhZY2Ww0MTwAzMzshFKGz2MLz2mxmxiNA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Egomaniaç-sargeras",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAwMzsMmxMDzYGmZZmZmBAAAAmNbz2DgZmBwsYmBjx2iFzMzUzCAmZbmlttJzyMzyAamlBLGDD",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Pws-azralon",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfzYAAAAAAAgxMmlxYmZYGGmZZmZmBAAAAmtZZ2YMzMAmlZMYY2YxMzM1AAzsMz2y2kZbmZZANz2gFz2wA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Misled-dragonmaw",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAmZmxsNzMzMDwwMLzMzMAAAAgtZZ2eAjZmBwsYMYYW2sYmZmaAgZ2wChxsNgGbwixwA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Adhd-dalaran",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAGmxsMzMzMDzwwMLzMzMAAAAwsNbzGjZmBwsYMYYW2sYmZmaAgZWmZZbbysNzsMgmZbwixwA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Copperjohn-chogall",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfDDzAAAAAAAAAAAAgxMLmZbmxysMzMzMzyYmtBzGzMzwsxsgxMDWWGqZGsBjZGMzilpmNDmlZZJjZ2YDA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Bestrussian-area-52",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfDDzAAAAAAAAAAAAgxMLmZbmxysMzMzMzyYmtBzGzMzwsxswMGDWWGqZGsBjZGMzitpmNDmtZZJjZ2YDA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Vål-blackrock",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYmHYMzMmZAAAAAAAz2MmtZAAAAAAollhZYmxYmZWGDmZMzMzMzYGW22GDGsNz2YjxMmlGz22wkthhlB",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Gærrøtè-undermine",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYMjZmxMDAAAAAAYWmxsNDAAAAAAtsMmBzMGzMzyYwMjZmZmZGzwy22YGgNzyADYJYZYCMsMA",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Jw-malorne",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYmHYMzMmZAAAAAAAz2MmtZAAAAAAollhZYmxYmZWGDmZMzMzMzYGW22GDGsNz2YjxMmlGz22wkthhlB",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Bodymasage-tichondrius",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMz2MzMjZMDzYYGGMjZmxMz02MmlZAAAAAAwyywMMzMzGsMGAAAAmZmBGMbzmZmZ0MzGzGLbTLsYA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Xygg-barthilas",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMz2MDMzMDzYYGmxMjZmxMz02MmlZAAAAAAwyywMMzMzGsMGAAAAmZmBGMbzmZmZ0MzGzGLbTLsZA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Jax-tichondrius",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0YG8AzwYMmZmZmxMmtxMGLLDzwMjxYmlxAAAAwMMDLmlZMbzwYhhlZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Möuthbläster-malganis",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzwCm5BMWmZmZwyMzyysMDAAAAAAAAAYDLYbZGzMLba22GmRzMNYBAz2kBzsYGzMjZmZGYzYa2YbmthZAAGD",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Askbotanical-sargeras",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMzyMDD2mZMPwMz2MzyyAAAAAAAAAAAsgllZMzssoZZbYGNz0gNAMbTmhxmxYmBzMzGWmx0stwMbjZGAgBA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Smrtdeath-zuljin",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMYWWmlZWmhFbLzsYjxMWmGbzsxkZyYhZGb2mZZmxoZ2MmZaYGGGLGzMbmtxysxAAAD",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Chillatech-tichondrius",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYmZmxMbjBz2ysMzyMsYZZmFLMmx20YZmFmMTGLMPwYzyMbMGNzyyYmpZMDDsYMzsZ2mZb2YAAgB",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Larâta-ragnaros",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMYWWmlZWmhNLLzsYjxM2mGLzswkZyYhZGbWmZjxMNzmxMTzYGmNwYmZzsNzysNAAAD",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Nesq-tichondrius",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbAzMzMzMjGz2gxsxMDzyAAAAmZMzyY4BWegZmZxMzMDAYmZZZZMMmFz0YmZYLzSG2mBAAAAAAAAMz2A",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Voidlockese-emerald-dream",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbwYmZmZmZEz2gxsxMjZWGAAAwMjZWGDPwiZmZxMzMDAwMLLLDMwMhZG2yIDbzAAAAAAAAgxMbD",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Menudoytacos-sargeras",
    ["code"] = "CoQAYIOwXTfhprvln24ZeRPDbwDwMzMzMjGzygxsxMjZWGAAAAAAAAAAmxyyMmZGWMZYmlZrNaGbMjZGbjZ2MzMzMzMjZYGzMDYGAAA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Voidelfs-whisperwind",
    ["code"] = "CsQAYIOwXTfhprvln24ZeRPDbAmZmZmZEz2gxsxMjZWmFjZmZmtZWYbxMDAAAAMzMsMzsMjNMzMmZZZ0Mzw2olZrxGGAAAAAAADzYAA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Magnuszx-zuljin",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGzMjZMPwsNLLLzMAAAAYGmmxYMzMbMGjBmZwwMjZAAAAAAAYmZWGjBQMjltZxMbDbGGmZmpFamBb",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Magnusz-zuljin",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGzMjZMPwsNLLLzMAAAAYGmmxYMzMbMGjBmZwwMjZAAAAAAAYmZWGjBQMjltZxMbDbGGmZmpNamBb",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Tractordaddy-zuljin",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGzMjZMPwsNLLLzMAAAAYGmmxYMzMbMGjBmZwwMjZAAAAAAAYmZWGjBQMjltZxMbDbGGmZmpFamBb",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Trustren-area-52",
    ["code"] = "CgEAO9DBjZzKcjSu6RJDto0RCCAAAAAAAAAjGzYMMzswsNwDswMjxwMjZmttxMzMzCMmxMzMjlhZGmZAAAgYssNwGYCmhJwMsB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Warriörgöd-moon-guard",
    ["code"] = "CgEAO9DBjZzKcjSu6RJDto0RCCAAAAAAAAAjGDzMbMDGzwYjZmZMMzYmZbbMzMzsxMDjZmZYZYmhZGAAAImZZbsxmtFz0YmZYysxMsB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Sailw-thrall",
    ["code"] = "CkEAO9DBjZzKcjSu6RJDto0RCKGAAAAmZmZMzMMz2MLzMzsBgYMGgBAMAAAAAAAAYmBAYZbDAAAEAgAA",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Graud-demon-soul",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAGzMz2sMwwMzwMmxgxAAgZGmZGjhZCmBAAAMzMTzgZmZbMDAMmZMbLbsZjhZmZaoZxMWMMA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Sleepiihead-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAGzMz2sMwYmZeAmZmxAGAAMzwMzYMMTYmBAAAMzMTzgZmZbMAAYMb2YBGYGN0wMWgB",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Sicklikeme-zangarmarsh",
    ["code"] = "CEcBV7//nP39x/JJympTqouKSwMLjtZmZGbGzMjZYmZGAAAAAgZAAwMzwMjxQNMzMAAAAYmZshZ2mZMwMGGmlZz2ysMMz2wMMz0I2gZA",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Happywhale-tichondrius",
    ["code"] = "CoPAtbMOTHlnKIwUyAn+DK70SjhZmZGYMjZsMzMmZaGmxYMjZAAAAAYGzMjxMz2MjxAAAMmZmZGAAAgZ22GDjZMbNW2WGmsNMsMAzwA",
    ["classId"] = 6,
    ["specId"] = 250,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Mes-stormscale",
    ["code"] = "CsPAtbMOTHlnKIwUyAn+DK70SPAMzMDMDjtxMmZmZYGzkhZMYwMMzMmZmZmZmlZGAAAAAAAAAAAgxy2sZ2mhxCDLzsNN0M2MmZYmZA",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Wegopher-tichondrius",
    ["code"] = "CwPAtbMOTHlnKIwUyAn+DK70SDgZmBMzMjlxMmZmGGGzMMDAAAAAAAAAmZMjxYmBAGmhZbGzMzMmZGD2mZzMzMamlNmNmtpxCDwMDA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Kciktep-tichondrius",
    ["code"] = "CwPAtbMOTHlnKIwUyAn+DK70SDgZmBMzMjlxMmZmGGGzMjZAAAAAAAAAwMjZMGzMAwwMMbzYmZmxMzYw2MbmZmRzsswsxsNNWAwMDA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Tygasoraw-tichondrius",
    ["code"] = "CwPAtbMOTHlnKIwUyAn+DK70SDgZmBjZMjlxMmZmGGGzMjZAAAAAAAAAwMjZMGzMAwwMMbzYmZmxMzYw2MbmZmRzsswsxsNNWYAMDA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Mvqx-illidan",
    ["code"] = "CEkAEDLOxe3SEPP2R8Hw6bhoSYGMzMzYMmZMmJDzAAAAAAAmlHYMmZmZmZbmZ2mlZZMMzwM22mlZWmlZmZW2mlppZYmZAL",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Chineseholyz-tichondrius",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAmZMzMjxMz0YMmZYMbzMMsNjZmhZGY2mZmFjxMMzAAAAwsNz2sMzMzy2sNNNDmZwsA",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Bound-blackrock",
    ["code"] = "CUkAEDLOxe3SEPP2R8Hw6bhoSAAmZMmZMMjMzMMDzMbjxMsNDzMmZMY2mZmNzMmZYGAAAAmtZwwYZhJZwMDjF",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Thugrose-blackrock",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlmxYmBY2GLzMzCDGmlZWmxyYmxMzixYmZmxGWAwYZbmtttZ2mlZamZZmCAABwmxYMwmxMG",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Slothfrmtree-sargeras",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlmxYmBY2mZZmZ2YgFzyMLzYbmZGzMLmlxwMshFAM22mZbbbmtZZmmZWmpAAQAsYMGDsZMjB",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Rfc-tichondrius",
    ["code"] = "CYGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAAAAAAALUmlmxYmBY2GLzMzCDGmlZWmxyYmxMzixYmZmxGWAwgZ222GbjZamZZUAAIA2MGjB2MmxA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Scuffedx-tichondrius",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzMjxMWmZMMjZGLeghZsMLDYxMGNRzY2MLzMzyYGGAAAAAAGMDAAgAqZWmlZmtBEgFYAYxMDD",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Munkiki-ragnaros",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzMzMjxyMz2YmZmBwwsYBMbzMGNRmZ2GLzMzCzAAAAAAYAMDYZbmNMmlRgpmZZWmZ2GQA2YMAsZMM",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Mopdruid-uther",
    ["code"] = "CgGAkuH5GdQpDrgY32rlVGnyqBAAAAAAAAAAAAzYMMzyMMjZMzYhZmxsMLDMbmxoJyMz2MLzMz2YGAAAAAAwwYALLzshxsMCMFAACwGMAssMwA",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Metaphorest-kelthuzad",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtZmZmtNjZmxmZZYYssx2ilZAAAAAAAAAAAAsMDZjx0MzMwsZWmZsYMMAAAAAwAGAALbjFMNzsNEAMLzs0sNziNGzYwMDQD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Samuelceo-area-52",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtZmZmtNDzM2MLDDjlN2WsMDAAAAAAAAAAAglZILMmmZmBmtZWmZmFMMAAAAAwAAYALLjFMNzsMEAMbzs0sNziNGzYwMDQD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Bluedru-tichondrius",
    ["code"] = "CkGAkuH5GdQpDrgY32rlVGnyqtZmZmtNjZmxmZZYYssx2ilZAAAAAAAAAAAAsMDZjx0MzMwsZWmZsYMMAAAAAwAGAALbjFMNzsNEAMLzs0sNziNGzYwMDQD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Jwz-tichondrius",
    ["code"] = "C0PAIKKe/J2LdooRW3uJg8yy0bstMjZmhFTWYWmZrhmxGAAAAAAGDbDzyMzMmZGmZmFmxMDmxMZGDzwMGzMMmZmZmZYMzw2ALAAAAAAAA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Yoske-tichondrius",
    ["code"] = "C0PAIKKe/J2LdooRW3uJg8yy0bstNjZmhNTWYWmZrhmxGAAAAAAGDbDzyMzMMzwMzsMmxMDmxMZGDzMzMGzMMmZmxMDjZw2ALAAAAAAAA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Robotwo-illidan",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmtlxwYbMTjlZWYLzSmFAAAAAAAAAAAAAAmBmZMjZmRmZmZGPwMMLzMsNwygZZmtx2MzMjZZmZYMzYbZMYZA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Looksmaxxing-illidan",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmtlxwYbMTjlZWYLzSmFAAAAAAAAAAAAAAmBmZMjZmRmZmZGPwMMLzMsNwygZZmtx2MzMjZZmZYMzYbZMYZA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Yøske-tichondrius",
    ["code"] = "C4PAIKKe/J2LdooRW3uJg8yy0bmttxwYZMTjlZWYJzSmFAAAAAAAAAAAAAAmBmZMjxMyMzMzYmhZZmhtBWGMLzsNbbzMzMmlxMMmZsYMGLD",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Jésús-dalaran",
    ["code"] = "C8PAIKKe/J2LdooRW3uJg8yy0PGMzMmtZZ0stMMjmZpBLzMz2MzMzYGjhZGmxYmZmNAAAAAAAoZMjZYmZmBGzMDzMMmZMbDsAAAAAAMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Junglejape-tichondrius",
    ["code"] = "C4DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMzGYmZYMNGjBAAAAAwABMzMtMLbzMzssssNzEbAAAAAAsBgxwMzysMmhxMzYmZmZmxMGD",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Pherìx-tichondrius",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMziBmZYaMPwgBAAAAAwMLz0MzysMzMtMLLzAAZxYGMMmxMzmZbMzMDmZbGLYMzAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Boømbam-bleeding-hollow",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMziBmZGTjxgBAAAAAwMLz0MzysMzMtMLLzAAZxYGMMmxMzmZbMzMDmZbGLYMzAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Polarpop-malganis",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYZmNLzMzMmZWGwYGTjZGMAAAAAAmZZmmZWmlZmplZbbGAILGzghxMzMzmZbMzYwMbzYBjZGAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Kúroko-area-52",
    ["code"] = "C8DAJHMkDNl9e4q1zfgySSx9jPYbmNLzMzMmZWGwYGTjZGMAAAAAAmZZmmZWmlZmplZZZGAILGzghxMmZ2MbjxMDmZbGLsMmZAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Dipiku-tichondrius",
    ["code"] = "CAEAJHMkDNl9e4q1zfgySSx9jPYZmNLzYmxMzC8AmZ0YMGzDMzwYMzMmZmZmZMzMzMzgxMLz0MzysABAAtAAAAAAgZBAAAAAAAA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Yusokmw-stormrage",
    ["code"] = "CwQACdq2zyOHcHaPcZ/HhhelgDAAAAjZGzgZWmx2YmZAAAAAAAYZBEzMwMM2gx2MzMmZhZGbzyMtt9Ab2mZGsAAAbIAAANbzSzMzsMmhNA",
    ["classId"] = 10,
    ["specId"] = 268,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Fraudcheck-tichondrius",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwyywImZmtxMbAw2MmZMbWYGzyMBAwyYmhZY2mBCgllZZZWmZmmtZpZmZWgBA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Goongob-tichondrius",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwyywImZmtxMbAw2MmZMbWYGzyMBAwyYmhZY2mBCgltZZZWmZmgAgBA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Halfstomp-tichondrius",
    ["code"] = "C0QACdq2zyOHcHaPcZ/HhhelgbmlxgZmhxMzYmZAAAAAAAAAAAwy2wImZmNmZDgx2MmZMbWYGzyMBAwyYmhZY2mBCgltZZZWmZmgAgBA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Dirtserpent-sargeras",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAADLzyYZYbz2YmxmZ22WmNwysZbmZZjZ0YmBmhZAzsNjZGzmlBmtZCAAAAwsMtNbzsMbWmllZbmZCCAA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Croagßoi-area-52",
    ["code"] = "C4QACdq2zyOHcHaPcZ/HhhelgDAAAAAAAAYZWGLDbb2GzM2Mz22ysBWmNbzMLbMjGzMwMMDYmtZMzYWsMwsNTAAAAAmlptZbmlZDAEEAYB",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Nahzbal-area-52",
    ["code"] = "CEEAN/WrsXv0CO5mzTm8Icl8KAAAAYAADAAgBYZYmxMbzMMzMLmxDsNgZbz0SjZWMMzwA2yAAGAsBsxsMzYmlZZmZWaAAzMLbLtMzwGGwYxMMzwMA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Michaelsmith-frostmourne",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsNj5BMzyYZMzMjx2MzMzMYYAAAGAAAAAAASmZWMMDGzMzWbAwYAAmBbDAAwMTbzysNDQgNDMAMzwwYA",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Cloudx-shattered-hand",
    ["code"] = "CIEAN/WrsXv0CO5mzTm8Icl8KsYmxYWmZZmZmZM2MmZMLMMAAADAAAAAAAt1MzsYYmZMMjtWAAGAgZw2AAAMz02sMbzMzsst02MjFgBgZYGDD",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Vegetable-suramar",
    ["code"] = "CAQAmmmbZv0rzNjRHT4p8IjZfDDw2MPwMGjZYGY2mZZmZmZ8AzAAAAAAAAAAAz2sMLMmZGAzyMzwMMbsYamJYAMzGWoYMbDwYBLAA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Teddipriest-tichondrius",
    ["code"] = "CAQAmmmbZv0rzNjRHT4p8IjZfDDw2MPwMGjZYGY2mxMzMzYmBAAAAAAAAAAmtZZ2YMzMAmFzMMDz2iFTzMBDgZ2wCFjZZAGLYBA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Uncle-suramar",
    ["code"] = "CAQAmmmbZv0rzNjRHT4p8IjZfDDw2MzwYMzAY2mZZmZmZMzAAAAAAAAAAAz2sMLMmZGAzyMGmhZbzipZmgBmZmZDLUMmtZWmtFjFjFbA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Mybackhurts-sargeras",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAMmZmlxMjZYGGmZZmZmBAAAAsNbzygZmBwsMjhZY2YxMzM1AAzsNz222kZbmZbANzygFjhB",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Kostikswd-illidan",
    ["code"] = "CEQAmmmbZv0rzNjRHT4p8IjZfDDAAAAAAAMmZmlxMjZYGGmZZmZmBAAAAmtZbWGMzMAmFjxYY2YxMzM1AAzsNzy22kZbmZbANz2gFjhB",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Løngløst-stormrage",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfDjZGAAAAAAAAAAAAMmZxMbzMWmlZmZGzywsNY2YmZwsxsgxMDzyysomZwCMmZAQBY2mllgZjNA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Sdvacxzvzxc-stormrage",
    ["code"] = "CIQAmmmbZv0rzNjRHT4p8IjZfDjZGAAAAAAAAAAAAwMLmZbmxys8AzMzYWmxsNY2YmZwsxsgxMDzyysomZwCMmZwMLWma2MY2mllMmZjNA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Mik-shandris",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYmHYMzMmZAAAAAAAz2MmtZAAAAAAollxMDzMYmZWGDmZMzMzMzYG222GzAsNz2YjxMmlGz22wkthhtB",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Vål-blackrock",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYmHYMzMmZAAAAAAAz2MmtZAAAAAAollhZYmxYmZWGDmZMzMzMzYGW22GDGsNz2YjxMmlGz22wkthhlB",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Gærrøtè-undermine",
    ["code"] = "CMQAA0tw2gAD7pPTLoW5IGZDeYMjZmxMDAAAAAAYWmxsNDAAAAAAtsMmBzMGzMzyYwMjZmZmZGzwy22YGgNzyADYJYZYCMsMA",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Däzëd-stormrage",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMz2MzMjZMDzYYGGMjZmxMz0yMmlZAAAAAAwyyYmhZmZWglxAAAAwMzAGMbzmZmZ0MzGzGLbTLsZA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Bodymasage-tichondrius",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMz2MzMjZMDzYYGGMjZmxMz02MmlZAAAAAAwyywMMzMzGsMGAAAAmZmBGMbzmZmZ0MzGzGLbTLsYA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Xygg-barthilas",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMz2MDMzMDzYYGmxMjZmxMz02MmlZAAAAAAwyywMMzMzGsMGAAAAmZmBGMbzmZmZ0MzGzGLbTLsZA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Yázim-tichondrius",
    ["code"] = "CQQAA0tw2gAD7pPTLoW5IGZDeAAMz2MzMjZMYmZYGGMjZmxMz0yMmlZAAAAAAwyyMzgZmZ2glxAAAAwMzAGMbzmZmZ0MzGzGLbTLsYA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Kalvish-dalaran",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0MzgHYGGDmZmZmZmxsNMmZZZYGmZwYmlxAAAAwMMDbmlZMLzwYhhtZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Jax-tichondrius",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0YG8AzwYMmZmZmxMmtxMGLLDzwMjxYmlxAAAAwMMDLmlZMbzwYhhlZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Dàzèd-stormrage",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0MzgHYGGDmZmZmZmxsNMmZZZMDmZMGzsMGAAAAmBDbmlZMbzwYhhlZ2mWolZBG",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Antijax-stormrage",
    ["code"] = "CUQAA0tw2gAD7pPTLoW5IGZDeAAMz2MAAAAAAMbjxy0YG8AzwYMmZmZmxMmtxMGLLDzwMjxYmlxAAAAwMMDLmlBGwCYZYCZWgB",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Vx-tichondrius",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2gBMBzGTIzCAYMNzwMbGjpxYmZglZMzsZMz2sxMzAzMLA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Wavedodger-tichondrius",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2gBMBzGTIzCAYMNzwMbGjpBzMDsMjZmNz2MbzGzMDMzsBA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Murasaza-drenden",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2WMzMsYyCz2MTDNzCAw20MDzsZMz0YmZmBWmxMDjZ2sxMzAzMbA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Roar-tichondrius",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2gBMBzGTIzCAYMNzwMbGjpxYmZglZMzsZMz2sxMzAzMbA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Frogtide-tichondrius",
    ["code"] = "CYQAL+iDLHPJSLC+6fqMJ8tubCAAAAAMLzy2MjZGzyswYMzYGDAAAAwiZ2gBMBzGTIzCAYMNzwMbGjpBzMDsMjZmNz2MbzGzMDMzsBA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Askminx-sargeras",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMzyMDPA2mZMzMz2MzyyAAAAAAAAAAAsgllZMzssoZZbYGNz0gNAMbTmhx22YMzMMzMbYxYa2WYmtxYAAGA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Askronnie-sargeras",
    ["code"] = "CcQAL+iDLHPJSLC+6fqMJ8tubOzMzyMDD2mZMPwMz2MzyyAAAAAAAAAAAsgllZMzssoZZbYGNz0gNAMbTmhx22YMzMMzMwyMmmtFmZbYGAgBA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Kaskä-tichondrius",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMMz2ysMWmhFbLzsYjxM2mGbzsxkZyYh5BmhlZMzYmmxyYmpxMDDsYMzsZ2GbzGDAAM",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Svondo-illidan",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMDz2ysMWmhNbLzsZjxMWmGbzsxkZyYjZGbWmZbmxoZW2GzMNmZYgFjZGGzsNbMAAYA",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Angryreubenx-sargeras",
    ["code"] = "CgQAL+iDLHPJSLC+6fqMJ8tubCAAAAAAAAAAYMzMmZbMYWWmlZWmhNbmZBGwEMbMhMWYmxmlZ2YMTzstMmZaMzwAMmZ2MbzsNbMAAwA",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Nosfive-bleeding-hollow",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbwDYmZmZmZEz2AmNmZMzyAAAAmZMzyY4BWMzMLmZmZAAzMLLLjhxsYmGzMDbZ2yw2MAAAAAAAAYMz2A",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Langneur-medivh",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbMMzMmZmhmZ2AmNmZMzyAAAAmZMz2Y4BWMzMLmZmZAAzMLLLjhxsYmGzMDbZWyw2MAAAAAAAAYMz2A",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Pxxd-kiljaeden",
    ["code"] = "CkQAYIOwXTfhprvln24ZeRPDbwYmZmZmZEz2MMmNmZYWGAAAwMjZWGDPwiZmZxMzMDAwMbLLjhxsYmGzMDbZ2yw2MAAAAAAAAYMz2A",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Rennarlock-tichondrius",
    ["code"] = "CoQAYIOwXTfhprvln24ZeRPDbwDwMzMzMjY2GWGzCzMmZZAAAAAAAAAAMGLLzYmZYzkhZ2mtWoZswMzMjtxMLmZmZGjZmhZMzMgZAAA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Baiw-tichondrius",
    ["code"] = "CoQAYIOwXTfhprvln24ZeRPDbwDwMzMzMjY2GWGzCzMmZZAAAAAAAAAAMGLLzYmZYzkhZWmlWoZswMzMjtxMLmZmZGjZmhZMzMgZAAA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Rosemarý-area-52",
    ["code"] = "CsQAYIOwXTfhprvln24ZeRPDbwDwMzMzMjY2GWGzGzMmZZMjZmZmlZ2YbxMDAAAAMzMsMzsMshZmxMLLjmZG2GtMbN2wAAAAAAAYYGDAA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Dadslapper-illidan",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGmZMjZmtZZZZMAAAAYGmmxYMzMLLGDM2MzghxYGAAAAAAAmZmlxYAWiZssNLmZbYzwwMzMtRzMYB",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Smaxxin-tichondrius",
    ["code"] = "CcEAO9DBjZzKcjSu6RJDto0RCCYbGmZMjZmtZZZZMAAAAYGmmxYMmZhZbwM2MzghxYGAAAAAAAmZmlxYAWiZssNLmZbYzwwMzMtQzMYB",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Rennarwar-illidan",
    ["code"] = "CgEAO9DBjZzKcjSu6RJDto0RCCAAAAAAAAAjGzYMMzssY2GwCzMGDzMmZ22GzMzMLwYGzMzMWGmZYmBAAAixy2AbgJYGmAzwG",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Clappyblappy-tichondrius",
    ["code"] = "CkEAO9DBjZzKcjSu6RJDto0RCKGAAAAmZmhZMjZWmZbGzstxYMTmxYmlFWGzMDbzMAMmBAAAAAAMzAAziNAGYDWWMaMDgZLmZD",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Naugom-stormrage",
    ["code"] = "CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAgxYmBzsZGzMYGGDTDzMZ2GLzMzMjZMzyMgZmZ2YmZbMDMwYwGsMGN2GQmJAbYA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Kamähleñ-malganis",
    ["code"] = "CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAAGzMMzsZGzMYGzYYaYmJz2YbGzMjZMzyMgZmZ2YmZbMDMwMzwGsMmlGbzMMZmsA2GG",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Truffleßutta-tichondrius",
    ["code"] = "CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAAGzMYmNzYmBzYGDTDzMZ2GLzMzMjZMzyMgZmZ2YmZbMDMwYwGsMGN2GQmJAbYA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Stælthßømbèr-baelgun",
    ["code"] = "CsbBV7//nP39x/JJympTqouKSAAAAAAAAAAAAGzMYmNzYmBzYGDTDzMZ2GLzMzMjZMzyMgZmZ2YmZbMDMwYwGsMGN2GQmJAbYA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Sleepiiheadx-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAGzMz2sMwwMzwMzMGwAAgZGmZGjhZCzMAAAgZmZaGMzMbjBAAjZzGLwAzohGmxCMA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Exrtj-stormrage",
    ["code"] = "CwbBV7//nP39x/JJympTqouKSAAAAAAmZmZ2mlBGzMzDwMzMGwAAgZGmZmZMMTwMAAAgZmZaGMzMbj5BAgxMjZbZjFbMMzMTDNbMWMMA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Buffdev-sargeras",
    ["code"] = "CEcBV7//nP39x/JJympTqouKSgZZmlZmZGbzwMz2wMzYAAAAAAAAAzMYGGzM1wMzAAAAAzMWYmZbMzAzsNMMLzmttZZYmthZYmpRshxM",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Myayongc-tichondrius",
    ["code"] = "CEcBV7//nP39x/JJympTqouKSgZZsNzMzYbGzMjhZmZmZDAAAAAGAAYmBzwYomxMzAAAAAzMzGzMbjZAGzYYWmNbLzywMbDzwMTjYDjB",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
};
