GSTLoadoutsDb = {
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Imaginedk-sargeras",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMAzMDjxMDzyMzMDmxoZmZmxYmZwYmZmZmZGzAAAAAAAAAgxsNbmtZYswwyMbTDNjFjZGmZgBghZGMzwAD",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Darksim-tichondrius",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBjZYYWYmZa2mZGzMjZAAAAAAAAMzwMDAWmxMDzMmxMGsNzmZMLaGYWY2mGLMAzAwYmZMDmZmZGzMG",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Ysdkt-tichondrius",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBjZMDzyYmZa2mxYmhZAAAAAAAAMzwMDAWmxYMzMmxMGsNzmZMLaGY2Y2mGLMAzAwYmZMDmZmZGzMG",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Mimsyoon-tichondrius",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAwMjZmZYYWmZmZaMzMzYGDAAAAAAAAzMMzAglZMmtZmxwMgNzihhMwsxQjFAMDAjZmxMAzMDzYA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Blade-khadgar",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORxgZmZYmxMjZmpZYAAAAAAAmlHYMmZmZmZbmZmlZbMjlZmZGbzsMzysMzMzy2sMNNDzYGLAAAAAAIAzMzMAABAAG",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Kokushibo-durotan",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMziZmZmZGzkhBAAAAAAYWMGz8AzMzsNzMzysNmxywMjtZWmZZWmZmZZbWmmmxMjZsAAAAAAgAMzMzgBgAAAD",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Smallsuper-azralon",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMDzMmZmZmJYAAAAAAAmFjZbmZmZmtZmZWmt5BmxygZsNzyMLzyMzMLbzy00MmZMjFAAAAAAEgZGgBgAAAD",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Aovilox-proudmoore",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBA2mZmZmZGzMGGAAAAAAALGjhZGAAAAAAAAmxMMzMzMjZmZmZmlZGjFtsxMzMzWbzMzAYGjZMmpZZmNDDMfA",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Renner-zuljin",
    ["code"] = "CkGA8cL7tpvige+kkmGM9zUPWPMmBzYmZmZZMzYMbMLMDAAAAAAAAAAWmhsZGTzMzMY2YmZmNDGAAAAAGAwYALbjNMNzsMAAmtZWa2mZxGzMzMYA0MAYmZmBgB",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Hogx-sargeras",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcYzsMjZmhFDLMzMbGaGbAAYGz2YmFzwMmZY8AzMGmxMzwYmllxMmZmxwoZGAAAAAYGAAAmhZGmZmZDZBzsAWMA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Briggsx-sargeras",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZb0stMMDzMNYzYmZMegl5BAAAAAAYGGzssMjhZMGzoZAAAAADAgltZmZxMzMzMMzAmZbG2WwMGzMLMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Retpar-demon-soul",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZegZDzMyMMDAAgZWmxMzysMzMNbLLzAAsZmxsNMmZWAAAAAgFzMzMAAwwMzghZWmBmZmZIzMmxwMMA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Aegzy-stormrage",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZxmZmYGmZMzMziZmxMjZmlZamZbWAAzMzssMz0GAAsAAAAsBw2yYmZGYZGzMzYBAAgZWmZwMMAAD",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Inyxa-bleeding-hollow",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzMjBMYbmZ2mBAAAAAAAAAAAYZYEmZ2wAYmxMjZGzmFGmlZCAYzMLzMMmZGIA2MzysMmmtZpZmZWAGzAzMzAMWYAzMzmB",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Slicingwinds-area-52",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8bmZMgZYbmZWmBAAAAAAAAAAAYZYEmZ2wgxwwMzMzYWsAmlZCAYzMLMzMzMzABwmZWmlx0sNLNzMzCwYGYmZGgxyMAzMzmB",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Valerie-dreadmaul",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8bGjBMjZbmZ2mZAAAAAAAAAAAALDjwMzGGwYGmZmxYWsMzDwsMTAAbmZZmxMmZGIA2wysMmmtZpZmZWAGGYmBAWmBYAfA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Walmartceo-alleria",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzMjBMYbmZ2mBAAAAAAAAAAAYbYEmZ2GGwwMmZmZY2mFGmlZCAYzMLzMmxMzABwmZWmlx0sNLNzMzCAGYmZGAWGAzMzmB",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Mightduy-black-dragonflight",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzYMghZZmZ2mxAAAAAAAAAAAALDzEmxywAmxwMzMDz2wMMLzEAwmZWGDjZmBCgNA0sMLNzMzCwwAzMAwCDYAD",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Yeonguo-drakthul",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMb2mxMjNDMjZ2MzmtZGbmZ0wMzCGMLwsNzYGmtZBMLzEAAAAYWm2mtZWmFbzsMLzMgAAY8BzMYGAgFZMDA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Loverimjobs-sargeras",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZGMjZ2MzmtZGbmZ0wMzGGMLwsNzYGmtZBMbzEAAAAYWm2mtZWmFbzsMLzMgAAY8BzMYGAgFZMDA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Captearthy-sargeras",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMWmZZMb2mxMjNDYMzmZ2sNzYjZ0wMgxYYYWmZMDz2sAmtZCAAAAMLTbz2MbzitZ2mlZGQAwgxMzgZADwiMmBA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Iildevo-tichondrius",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZGMjZ2MzmtZGbY0MmBMYWYMbzMzMMbzCY2mJAAAAwsMtNbzsML2mZZWmZABADGfwMDmBAYRGzA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Cd-blackwing-lair",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZgZMzmZ2sNzYjZ0wMzGGMLwsNzYGmtZBMbzEAAAAYWm2mtZWmFbzsMLzMgAAYMzMYGAglJjZA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Trpblitzer-stormrage",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzMLzwYGbjtZmNmmYWmhZwgtMAMAsB2YzMzsMLzMzSDAYmZbbx2MDbsxwYzMMzwwMAmZwMjxgRD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Kenolol-sargeras",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglxMYmlZGLzwYGbjtZmFmmYWmhZmxgtMAMAsB2YzMzsMLzMzSDAYmZZbxyMDbsxwYzMYGzwMAmZAwAaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Addison-ravencrest",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzYZGzYGbjNzsw0EzywMzwgtMAMAsB2MbmZAQAAzMLbLWmZYjtxwYjZMzwwMAmZAwgRD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Shufbrainrot-tichondrius",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhZmZmlZmZxwAbzsNzsw0EzyMMzwgtMAMAsB2MbmZmlZZmZ2aAAzMLbL2mZYjNGYzMDzwAAmZwMDGDaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Xbabayagax-illidan",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhhZmlZGLGzYGbjNzsw0EzyMMzwgtMAMAsB2MbmZAQAAzMLbLWmZYjtxwYzMMDzwMAmZAwAaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Gobbysmalls-frostmourne",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsNGWmZMGzwMbzYmZGjZGAAAAAAAAAAzY2mBDzYZGzMstYamYGmZmZBDhxsMzystYMGLGAAGzMGDmBzMzMzEM",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Bestworld-moon-guard",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsYGWmZMzMgZbGzMzMjZGAAAAAAAAAAzMzyAjZGLzMzMmFmmJGMzMzGGCjZZmtZZzYMWMAAMmBGmBwMzMBD",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Lileynth-moon-guard",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsYY2YMzMzMjZbGMzYYGAAAAAAAAAAzw2MYmZGLYmxstYamYGmZmZDDhxYmlZbxYM2MAAMmZmxgZwMjxoZYA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Illicitheals-area-52",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADswwyMzMYGmZbmtZmZmxMDAAAAAAAAAgZmZZGMmZsNjZGw0MxAMzCGCjZZAGDWAAgh5BmxgZAmZmJYA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Bigvuqoffdam-area-52",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAwYmxsMzMmZGDzwMbzMmBAAAwMjFDzYMWmZmZYZxYmCgZ2MLjJz2Mz2AMzMYxMzAQzwYGDGAzMzAfA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Intervention-black-dragonflight",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4ywYAAAAAAAmxMmlZmxMDYGmZbmZmBAAAwMzsMDGjxiZGDLLGzUAMz2MbzMZ2mZ2GgZmBLMzsAoZMjZMYssNYmZG4DA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Sleboz-moon-guard",
    ["code"] = "CQQAByFP3pExAEG41/8+e6b8fDgBzMmZmxMbmZmx4BMbmZegZMtNYZGAAAAAgtlZmZmZmZmZMzMbDAAAgZAMY2mNzMzoZmNmNW2mWYBAzMzMzgB",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Nahj-tichondrius",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbMmZMDmZmZmlxsNMzssMMYmxAmxAAAAYGMwsMjZbGGLMYmtpFaZ2YmBzMzgZmB",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Commodore-dalaran",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsMmZmllxMYmxAmxAAAAYGMwsMjZbGGLMYmtpFaZ2YmBzMzgZMA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Snortedgfuel-drenden",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgx2MAAAAAwsMGLTMbbjxMMjxDMzMzYMbzYGLbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Rats-ghostlands",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbMmZMDmZmZmlxsMMzssMMYmxAmxAAAAwwMsYWmxsNDjFG2mZbahWmNmZYmZmBzMD",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Dxlöl-quelthalas",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjFmZ2GLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Nobi-malganis",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAgBAAAAjZMLbLzYmZmZmZGzYssMziNGzYZasNzCTmhxGjZwsNGjmtFzsYmZwixMjZmtZzAAwAMzMYmBzMMGM",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Rykelinz-illidan",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESotMGzMjmtZGLMzMLzCzYWmxssYGAAMzMmZmFbwAziRjZAMbxGDAAMGYsBAMzgZmxYAAAYGzAAwYYA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Subfive-stormrage",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4DzMzsNzMzMDAAAghphZGmZhZegZGzYmZAAAAAMWmZAxMW2mNjthNDDzMz0CNzgNwMsYWmZWYYAzMDAzYYA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Vengarl-aegwynn",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMz4BwMzYGzMzsMzMzYmZZMzMAAQMzyyYjFLLmpxMzwkZjZGLAmZxMLDAmZwMjhhxwgB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Gloxx-darkspear",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMjZWYmZGjxMzYGzMzsMzMzYMLjZmBAAiZWWGbsYZxMNmZGmMbMzYBwMLGLDAmZwMjhxMGGM",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Nautìk-kelthuzad",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDjZmZWYmZmZwMzYGzMzsNzMzYMLjZmBAAiZ22GbsZZxMNmZGmMbMzYBwMLGLDAmZAmhhxghB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Grimfate-boulderfist",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGYmZmxymZmZMYmZMjZmZWmZMjxsYmZGAAImZZbsxmlFjGzMDTmNMjFAzsYsMAYmBmhxMzMDDG",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 5,
    ["name"] = "Degradation-dalaran",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMzYMmZGzYmZmlZmZGjZZMzMAAQYgNYZxoxMgMbYYBwMLGLDAmZAmhhxwgB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Isperia-area-52",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAwMzMzgZYGmZMzMGDTjZmpZMWmxMzMzYmZGwMzYwMLjZgBMzMWYxyYWasNzwkZyGYbYgZmZGMA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Boa-moon-guard",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2WGYYmZwMGsNMAAYmhZmxYYmGzMDAAAsNzMTzgZmZZMAgxMjZW2YxCDzMz0QzGjFDjZGMzMGA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 2,
    ["name"] = "Tailuñg-illidan",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZwMGsNMAAwMMzMGjHYmYmZAAAgtZmZaGMzMbjZAgxMjZW2YxCDzMz0QzGjNDjZGMzwA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 3,
    ["name"] = "Dracob-sargeras",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZYmBsNMAAwMMzMGDzEzMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzmZsYYMzgZGGA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 4,
    ["name"] = "Castoria-bleeding-hollow",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2MwwMjZxMGsMAAAzMjxMYYmMzMDAAAsNzMTzgZmxMzAAwYGbsADMjGaYGLwYmBYMA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "2v2",
    ["rank"] = 1,
    ["name"] = "Xaeyn-moon-guard",
    ["code"] = "CEcBPJc41CfcseY0baneJ1IHrNmZmZbmZmxyAzsMjxwMAAAAAAAAwMwMGjpGzMzAAAAAzMzMmZWGzMwMbGDzyMWWmlhZ2GmhZmGxGmZGMzAYA",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Petkick-sargeras",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmZYMDDzyYmZa2mxYmhZAAAAAAAAMzwMDAWmxMjZmxwMGsNzmZMLaGY2Y2mGLMAzAwYmZMDmZmZGzMG",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Kidseeghost-tichondrius",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmhhZMMzyYmZa2mZGjZMDAAAAAAAgZGmZAwyMmZMzMmxAsZWMMkBmNGaswAMDAjZmxMAzMjZGD",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Jungolifena-tichondrius",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBMzYMzyYmZa2mZGjZMDAAAAAAAgZGmZAwyMGjZmxMmxgtZ2MzMLamlFmNmtpxCDwMAMmZGzAMzMmZMA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Endofdays-thrall",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBjZYMzyYmZa2mxYmhZAAAAAAAAMzwMDAWmxYMzMmxMGsNzmZMLaGY2Y2mGLMAzAwYmZMDmZmZGzMG",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Mvqdh-illidan",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMDzMmZmxMZYAAAAAAAmFjZbmZmZmtZmZWmtxMWGmZsNzyMLzyMzMLbzy00MmZMjFAAAAAAEgZmZGMAEAAYA",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Deixasarrath-tichondrius",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMDzMmZmZmJDDAAAAAAwsYMmZmZmZbmZmlZbMjlhxYbmlZWmlZmZWWmlppZMzYGLAAAADAABYmZmBDABAAG",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Croces-daggerspine",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMzyMmZmZmZmMMAAAAAAAzixsNMzMz2MzMLz2YmZZwM2mZZmlZZmZmltZZaaGzMmxCAAAAAACwMzMDGACAAM",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Morgoph-bleeding-hollow",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZmZMzMzyMmZmZGzkhBAAAAAAYWMmtZMzMz2MzYZ2YGLDmx2MLzsMLzMzssNLTTzMzMmxCAAAAAACwMzMDGACAAM",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Papsiedh-area-52",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmxMzMzMzMGmBAAAAAAYxYMMzAAAAAAAAwMmh5BmZmZMzMjZmFz4BsolNmZmZ2abmZGAzwMz2Mz0sMzyMjBmB",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Týbur-area-52",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMLNjxMDwsNzMzMbMwMLjlZMjZmtxyMGzMYDDAGbbzMbbzsNLz0MzyMBAAAYzMzMzgNjZMGAmZwMDMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Eriang-bleeding-hollow",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMLNjxMDwsZmZmZhhhZZmlZMjZGjFjZmZY2wwAM2Wmx22Mb2MNzsNTAAAA2MzMjBbGGjZAMzgZGsMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Patspencer-bleeding-hollow",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMLNjxMD8AmNzMzMbMwMLjlZMjZYsMjZmZwGGAM22mZ22mZbWmpZmlZCAAAwmZmZmBbGzYMDgZGMzADA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Wakeenfiendx-tichondrius",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMbwgZbmlZMjZGsMjZmZwGGAM22mx22Mbz2MNzsMTAAAA2YmZmBbGzYMDgZGAsMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Zaydn-tichondrius",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMLNjxMDwsNzMzMLMwMLzsMjZMDjFjZmZwGGAM22mZW2mZb2mpZmlZCAAAwmZmZMYzYGjZAMzgZGsMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Zentheon-malganis",
    ["code"] = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAjZWYmZmZGz2CLzsMjZMzMAAAAsEMbGYmZqZMbmZmZWGz8AGAAAAAAgBAAAQzsMbzMzMLzs1sNzyGMzMALMYAAMzgZ2wA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Ninelivesz-proudmoore",
    ["code"] = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAwYMDmZmZmxstMWmZZGz4BmZAAAAYJY2MwMzUzY2MzMzsNmhBAAAAAAYAAAA0MLz2MzMz2MLNbzssBzMDwCzwAAYmBGYA",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Vctrphs-nemesis",
    ["code"] = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAAzMWYmZmZGz2yYZmlZMz8AzMAAAAsEMbGYmZqZMbmZmZWGzMGAAAAAAAAAAAamlZZMmZZmlmtZW2AzMALGYAAMzAgB",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Borkdru-area-52",
    ["code"] = "CcGA8cL7tpvige+kkmGM9zUPWDAAAAAgZMDGzMzMmtlxyMLzYm5BmZAAAAYJY2MwMzUzY2MzMzsNmhBAAAAAAYAAAA0MLz2YMz2MLNbzssBzMDwCzwAAYmBAD",
    ["classId"] = 11,
    ["specId"] = 103,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Moxie-moon-guard",
    ["code"] = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmxsMMjZWMLzDMzMWGY2MMaimZmlxMzMLjZGAAAAAADLzAW2mZwYWGATNzysMzMDAgFjZeAgFGMYsgBYmZmFYA",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Zyhsul-emerald-dream",
    ["code"] = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmxsMPwMeg5BWMbDzMLLDYzwMNNTzMzmZmZsMmhBAAAAAMsMDYZbmBjZZAM1MLzyMzMAAWMmBwiZwghZxAYmZ2gB",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Renner-zuljin",
    ["code"] = "CkGA8cL7tpvige+kkmGM9zUPWPMmBzYmZmZZMzYMbMLMDAAAAAAAAAAWmhsZGTzMzMY2YmZmNDGAAAAAGAwYALbjNMNzsMAAmtZWa2mZxGzMzMYA0MAYmZmBgB",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Vêlleity-sargeras",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZWGDjZMTjlBWyMMbAAAAAAAAAzAzssMjHYmZmxwoZMmZmtlNzMzwMDbzYbMmlhZGAAwMMzAwMstMMDwywA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Inyabusiness-tichondrius",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZWGDjZMTjlZGWyMMbAAAAAAAAAzwYYxYmZmZMmRzYMzMbLbmZGMzw2Mz2YMLDzAAAMzYmhZGMzYDmBYZYA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Grenades-destromath",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZWGDjZMTjlBWyMMbAAAAAAAAAzwYGLzYGzMjhRzYMmZbbzMzMMzw2M2GjZZYmBAAMzYmBgZGbLYGgthB",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Drßòb-area-52",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYbZ2GDjZMTjlZGWyMMbAAAAAAAAAzAzYxYmZmZMmRzYMzMbLbmZGMzw2Mz2YMLDzAAAMzYmhZGMzYbBzAYYA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Hornyhoofs-malganis",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZ2GDjZMTjlZgMDzGAAAAAAAAwMGmxixMzMzghmxYmZ2W2MzMDzMYGLjxsMMzAAAmhZGAmZstgZA2GG",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Jaywaz-tichondrius",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZb0ssMMDzMNYzYmZMzDsMPAAAAAAAzMzYGmxYGzMMmmBAAAAAAw22MzsYmZmZMmBYmtZYZBzYMjNG",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Shoop-saurfang",
    ["code"] = "C4DAMhlVtghLZL4RZzExaQoBYNstMzyMzML2mZGawMAAAGAwMz0sstMzMzMLLzMxCAALzwMjxilZmZMzMjxMzMjFmZmxMAADAAgZ2wMDMGAMM",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Kalvishmage-dalaran",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmllZWmZmZBzMyMjZAAAMzyMmZ2mlZmpZbZZGAgNzMmtxMzMPwCAAAAAsYmZGAAwwMzgxMzyMwMzMDZMwwMMA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Pherìx-sargeras",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZBzMyMMDAAgZWmxMzysMzMNLLLzAAsZmxsNmZmZWAAAAAgFzMzMAAwwMzgxMzy8AwMzMDZMwwMMA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Ntm-stormrage",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZDzMyMMDAAgZWmxMz2sMzMNbLbzAAsZmZmthxMzCAAAAAsYmZmBAAGmZGmhZWmBmZmZIjBGmhB",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Icarryegirls-tichondrius",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZxmZGZeAmBAAwMLzYmZbWmZmmtllZAA2MzY2GzMzYBAAAAAWMzMzAAADjZGGzMLzAzMzMkxYYYGG",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Fujikaze-kelthuzad",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzMLzyDMzEDmZmZmZYmZMzYmZZmmZWmFAwMzMLLzMtBAALAAAAbAssMmZmB2MGzMWAAAYmNgZYMgZwA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Oldboy-moon-guard",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzML2mZmYeAmZmZmZWMzMmZMzsMTzMbzCAYmZmllZm2AAgFAAAgNA2WGzMzALGjZmlFAAAmZBYGGAgB",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Chez-tichondrius",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZxmZmYGmZmZmZWMzMmZMzsMTzMbzCAYmZmllZm2AAgFAAAgNA2WGzMzALGjZmlFAAAmZBYGGAgB",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Paradox-kul-tiras",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzMjBMYbmZ2mBAAAAAAAAAAAYbYEmZ2GGAmxMjZGz2swwsMTAAbmZZmhZmZGIA2MzysMmmtZpZmZWAGGYmZGAWYMYmZ28B",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Briån-bleeding-hollow",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8bmZmBmZYbGz2MAAAAAAAAAAAAbDjwMz2wAwMmZAz2sMzwsMTAAbmZZmxMzMzABwmZWmlx0sNLNzMzCAzAzMzAM2YwYmZ2cB",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Meepmonk-kilrogg",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZgFjZGLzMLbLzYgZx2MjNmRzYGLYwsYGz2YmZY2mFMmtRAAAAgZZab2mZbWsMzysMzACAGMmZGMDAAZMDA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Melyon-tichondrius",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZmNMmZzMb2mZshRzYGwgBMbzMzgZbWAz2MBAAAAmlptZbmlZx2MLzyMDIAYw4DmZwMgxALTGzA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Supergator-sargeras",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAAmZWmZZMb2mxMjNDYMzmZ2sNzYjZ0wMgxYWgZbmZmhZbWAz2MBAAAAmlptxwsYbmtZZmBEAMY8BzMYGwAsIjZA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Nhyftwò-illidan",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZgFjZGLzMLbLzYgZx2MjNmRzYGLYwsYGz2YmZY2mFMmtRAAAAgZZab2mZbWsMzysMzACAGMmZGMDAAZMDA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Mistrweaver-dalaran",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMb2mxMjNDYMzmZ2sNzYjZ0wM2wgBMbzMzMMbzCGz2MBAAAAmlptZbmlZz2Mbz2MDIAAGzMDmBMALyYGA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Montage-illidan",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAMLAgZAAGsMMYmlZGLzYGzYbsZmFz0EzyMMDGslBgBgNwGbmZAQAAzMLbLWmZYjNGGbmhZGGmBwMDAGMaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Jd-anetheron",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhZGzsMzYxYGzYbsZmFjmYWmhZwwDslBgBgNwmZzMzsMbzMzWDAYmZZbxyMDbsxAbmhZYGmBwMDmZwgRD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Kosakî-proudmoore",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzYxMzYGbjNzsY0EzyMMDGslBgBgNwmZzMDACAYmZZbxyMDbsNGYzMMDzwMAmZAwYMaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Memoriesonly-area-52",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzYxMzYGbjtZmFmmYWmhZGGslBgBgNwmZzMzsMLzMzSDAYmZZbxyMDbsxwYzMYGzwMAmZAwAaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Bubblebuddyy-illidan",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhZGzsMzMLGGDbjtZmFmmYWmhZGGslBgBgNwmZbGzsMLzMzSDAYmZZbx2MDbsNGGbmhZYGMAmZwMDGQD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Vanguards-tichondrius",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsNmZGDAAAAAwMlZZGmhthZbwsMjHwYmhZsx2AwsMbzMzSzMTbzMbzAA2AMAGjZYGMjxshlZmZGGDDG",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Vânguards-tichondrius",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsNmZGDAAAAAwMlZZGmhthZbwsMjHwYmhZsx2AwsMbjZWyMTbzMbzAA2AMAGjZYGMjxshlZGzwYYwA",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Zozo-zuljin",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQzy2MzsNmZGDAAAAAwMlZZGmZsN8AbDmtZ8AGzMMjN2GGwsNbzMzSzMTbzMbzAA2AMAGjZ2AmxY2wyMYYMMYA",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Zelowrath-tichondrius",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsNmZGDAAAAAwMlZZGmhtZ8AbDmlZ8AGzMMjN2GAmlZbmZWamZabmZbGAwGgBwYMDzgZMmNsMzMzwYYwA",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Kistorm-tichondrius",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMzwCjZmZmxMbzwMzYYGAAAAAAAAAAjZWmZMDGLmZmhlFTzEzwMzMbYIMmtZWmtFjxYxAAwYGmZYGYmZmZmgB",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Pisaki-anvilmar",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsAz2DYMzMzMjZDmZmZYGAAAAAAAAAAzM2GMzMGLzYmhlFTzEzwMzMLAhhlZWmtFDGbGAAGzYGDGYmBz0MM",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Plaedo-stormscale",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMGWmZMzMwMbzYmZGjZGAAAAAAAAAAzMWmBzMzYxMzMssYamYwMzMbYIMmlZWmtFjxYxAAwYGDDGAzMzEM",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Caveria-emerald-dream",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAwYmxsMzMzMDDzwMbzMzMAAAAmZmFGzMjxyMmZYbxYmCgZ2MLjJz2Mz2AMzMYhZAQzwwYwAYmZGYA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Pillahump-tichondrius",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4ywYAAAAAAAmxMmlZmxMDYGmZbmZmBAAAwMzsMDGjxiZGDLLGzUAMz2MbzMZ2mZ2GgZmBLMzsAoZMjZMYssNYmZG4DA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Sped-saurfang",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yYYMGAAAAAAAAAAAADLzMGLzMmZ2mZYmx2YGzMzYZMZYZx0AMzMDmZxMa2MY2mtlMmZjBYMzgxMjxsMmZbZmZwMYA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Yogg-tichondrius",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yMYYGAAAAAAAAAAAAMLmxMLzMmZ2mxYmx2MGzMzYhJDLLmGgZmZwMLmRzmBz2sslxMbMAjZGMmZmxswMYmBzgB",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Xygg-barthilas",
    ["code"] = "CQQAByFP3pExAEG41/8+e6b8fDgZYwYGmZbmZmZGPgZZxMzMLTbD2mBAAAAAYZZmZMzMzMzYmZMAAAAmhBGMbzmZmZ0MzGzGLbTLswAMzMzMwA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Ozzthegreat-illidan",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsNmZssMmZYmxAmxAAAAwwMsYWmxsNDjFGWmZbahWmNmZYmZmBzYA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Kalvish-dalaran",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmlZmZZiZZbmZmZMDMzMzsMmthZmllhBzMGwMGAAAAGmhFzyMmtZYsww2MbTL0ysxMDzMzMYmZA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Eitheror-drenden",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsNmZssMmBzMGwMGAAAAzwMsY2mxsNDjFG2mZbahWmNmZYmZmBzYA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Thèllè-sargeras",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmlZmZZiZZbmxMjZgZmZmlxsNmZssMmBzMGwMGAAAAzwMAGzmhBGY20CtYjZGwMDmxA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Väl-blackrock",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbMmZMDmZmZmlxsMMzssMMYmxAmxAAAAwwMsYWmxsNDjFG2mZbahWmNmZYmZmBzMD",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Saul-tichondrius",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjFmZ2GLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Tech-laughing-skull",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjlxMzGLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Maraudertko-moon-guard",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZmZmZmZmxMzYGAAAAAAAAgNsgtlZMzssoZbbYGmZawCAz2MMGLLzYhZmtxiZmZYmNmBAwwwwMTMzMzgBjPA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Earthquake-sargeras",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjFmZ2GLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Biglawnmower-tichondrius",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMzMDzMzMmZmZGzAAAAAAAAAALYbZGzMLLaW2GmhZmGsBwsMMjZ22mxiZmxMLzYmhx2wAAAzMzYmJmZmZwgxHA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Nobi-malganis",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAgBAAAAjZMLbLzYmZmZmZGzYssMziNGzYZasNzCTmhxGjZwsNGjmtFzsYmZwixMjZmtZzAAwAMzMYmBzMMGM",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Katucadao-sargeras",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESotMGzMjmNzYhZmZZAAAAAAAGLLzYmZYzwwMLzWL0M2MmZsNmxMjBAmZmhZAmZmZGzMAAAjZMjxMsNzAMA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Bigboltx-ragnaros",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESoZmhZGNLzM2YmZWmFmxsMjZbxMAAYmZMzMLWwMzYmllRzMDbDLzWjNGAAYAmZDAYmBzMzMGAAAmZmBAgxwA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Agb-skullcrusher",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESotMGzMjmtZGbMzMLjhxsMjZbxMAAYMjZmZxGmZGzssMamZYZYZ2asxAAADwMbAAzMYmZMGAAAmxMAAMzwA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Isnlonely-tichondrius",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmZmlZmZGDAAAghxwMzYmFmZmhZYmBAAAAwYxMwGmxy2sYmthNDDzMzYDzMDLAzYZmlxsxMbDmZAAYYA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Río-area-52",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4DzMzsNzMzYAAAAMMhxMzYxMzMDzYmZAAAAAMWMDslZGLbziZ2G2MMMzMTL0MDWAmxiZZMbMz2gZmZGAmxwA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Bingbingbing-kelthuzad",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMzYwMzYGzMzsNzMzYMLjZmBAAiZ22GLsZZxMNmZGmMbMzYBwMLGLDAmZAmhhxwgB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Swim-shadowsong",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMjZW2MzMjBzMjZMzMzyMDjxsMmZGAAImZZbsxmlFz0YmZYysxMjFAzsYsMAYmBwwMzYYGG",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Darkoil-illidan",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMjZW2MzMjBzMjZMzMzyMzYMzsMmZGAAImZZbsxmlNz0YmZYysxMjFAzsYsMAYmBwwYGDDG",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 4,
    ["name"] = "Flokk-sargeras",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMzYwMzYGzMzsMjxYMLjZmBAAiZW2GLsZZzMNmZGmMbMzYBwMLGLDAmZAmhZMGmhB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 5,
    ["name"] = "Mud-icecrown",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMz4BwMzMzYmZmlZGGjZZMzMAAQMzy2YjNbLmpxMzwkZjZGLAmZxMLDAmZwMjhxMGmhB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Disintegon-sargeras",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMzgZYGmhZGzYMTjZmpZmxyMMzMzYmZGwMzAmZZmZgBYwGsMGN2GQmJAbYgZGMjB",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Coraloop-silvermoon",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAgZmZGMDzwMYGzYMTzMzMNjxyMmZmZGzMzAmZmBzMLjZgBGD2glxox2AyMBYDDMzAMA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 3,
    ["name"] = "Tappyÿ-tichondrius",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMDMDzwMMzgZMTjZmpZMWmxMzMz8AzMzAmZmZYmZZMDMwMzwGsMmlGbzMMZmsA2GGYmBYA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 1,
    ["name"] = "Zaegorn-stormreaver",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZwMGsNMAAwMMzMzYYmwMDAAAsNzMTzYMzMLjZAgxMjZW2YxCDzMz0QzGjFDjZGMzwA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "3v3",
    ["rank"] = 2,
    ["name"] = "Hyttzdrag-hakkar",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2MwwMzwMjHAbDDAAMDzMjxwMNmZGAAAYbmZmmxYmZMmBAGzMmZZjFLMMzMTDNbmxihxMDmZYA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 1,
    ["name"] = "Isnlonely-tichondrius",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmZmlZmZGDAAAghxwMzYmFmZmhZYmBAAAAwYxMwGmxy2sYmthNDDzMzYDzMDLAzYZmlxsxMbDmZAAYYA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 2,
    ["name"] = "Diuneimkone-tichondrius",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4DzMzsNzMzYAAAAMMNMmxMLLzMzMYYmBAAAAwYxMwWMjltZxMbDbGGmZmpFamBLAzYZmlZmNmZbwMDAwYYA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 1,
    ["name"] = "Magnusz-zuljin",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMzYwMzYGzMzsMjxYMLjZmBAAiZW2GbsZZzoxMzwkZDzYBwMLGLDAmZgZmhxMGmhB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 2,
    ["name"] = "Fullyhollow-proudmoore",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMWYmZGDmZGzYmZmlZmxYMLjZmBAAiZW2GbsZZxoxMzwkZDzYBwMLGLDAmZgZmhxMzwgB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 3,
    ["name"] = "Qfiendtwo-stormrage",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMzMzCzMzYwMzYGzMzsMzMGjZZMzMAAQMzy2YjNLLGNmZGmMbYGLAmZxYZAwMDMzMMmxwgB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 4,
    ["name"] = "Cõpe-barthilas",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDzMjZWYmZmZMmZGzYmZmlZmxYMLjZmBAAiZW2GbsZZzMNmZGmMbMGLAmZxYZAwMDghxMGmhB",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 5,
    ["name"] = "Noxite-saurfang",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAgGDjZMjlZmZGzMjZGzYGzsMzMGzMLjZmBAACDsBLLGNmBkZBzYBwMY2GAMzAYYmZGMYA",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 1,
    ["name"] = "Jjokai-ragnaros",
    ["code"] = "CkEAjLzRlq54bI5v+r8Sr9Xw43CAAYmZYmZmZGzGzsN8AGjmZmZmNzYmZYYmBAAAALzMAzYAGssNjZbZb0MzwMsMLNmZDmZmZYGDAmZAAwAG",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "shuffle_warrior_fury",
    ["rank"] = 2,
    ["name"] = "Termana-azjolnerub",
    ["code"] = "CkEAjLzRlq54bI5v+r8Sr9Xw43yAAAzMDzMzMzMzmxsMMGjGGDLzMzMDzYmBAAAALjBYGDwAbwyiRjZAMLxMbwMmZwsNAYmBAgZAD",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "shuffle_paladin_protection",
    ["rank"] = 1,
    ["name"] = "Aluvia-malygos",
    ["code"] = "CIEAVg1HmQqr1Dwlv86ljju8vuNjBWmZZMzMzMWYmhZhhBAYAAAAAAQTzMLzMmZGzM2aDADAMw2AAAzMtNzsNzMzy2SbzMWMDGGYMmhxAgZmlZgxMAD",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "shuffle_paladin_protection",
    ["rank"] = 2,
    ["name"] = "Mortalux-area-52",
    ["code"] = "CIEAVg1HmQqr1Dwlv86ljju8vuNjxYWGLjZmZmZZhZGmFLDDAwAAAAAAgmmZWmZMzwMsFAMAwMYbAAgZm2mZWmZmZZbplZGLmBDDMYGzYAwMz2MAzMgB",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "shuffle_shaman_restoration",
    ["rank"] = 1,
    ["name"] = "Tmdumptruck-tichondrius",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAgBAAAAjZMLbLjZmxMzMzMzYmllZWsxYGLTjtZWYyMM2YMDmtZGz0stYGmxgFjZGzMbzmBAAAzMDmZwMDjBD",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "shuffle_shaman_restoration",
    ["rank"] = 2,
    ["name"] = "Joxibaba-stormrage",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAAAAAAYMzM2WmxMMzMzMzMGLLjFbMmxiGbzswkZYsxMzgZ7BmZGNLLmZhxglZMz8AzMbzGAAAYmZwMDmZYmBD",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "shuffle_shaman_restoration",
    ["rank"] = 3,
    ["name"] = "Samoanflow-tichondrius",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAgBAAAAjZmZZbZGzwMzMzMzYmllxiNGzYRjtZWYyMM2YMDmtxMjmlFzswYwyMmZMzsNbDAAAMzMYmBzMMGM",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "shuffle_shaman_restoration",
    ["rank"] = 4,
    ["name"] = "Bluemandan-garrosh",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAgBAAAAjZmx2yMmZMzMjZmxYZZmNbMmxy0YbmNmMDjNmZGMbjZGNLLmZhxglZMz8AzMbzGAAAwMDmZwMDzMYA",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "shuffle_shaman_restoration",
    ["rank"] = 5,
    ["name"] = "Svondo-illidan",
    ["code"] = "CgQARUG2fGwHkLP0T7/MoTNl/AAAAgBAAAAjZmx2yMmhZmZmZmxYZZsYjxMW0YbmFmMDjNmZGMbjZGNLLmZxMGsMjZGzMbzGAAAwMDmZwMDzMYA",
    ["classId"] = 7,
    ["specId"] = 264,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 1,
    ["name"] = "Facelazer-stormrage",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMzgZYmxMMzYGDTjZmpZMWmxMzMzYmZGwMzYYmZZmZgBMzwGsMmlGbzMMZmsA2GGYmBDD",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 2,
    ["name"] = "Stælthßomber-tichondrius",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMzgZYGzMjZmxY8ATjZmJzMWmZmZGzYmZGgZGwMLzMDMADWglxox2AyMBYDDMzghB",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 3,
    ["name"] = "Enivhud-malganis",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMzgZYGzMjZmBjZamZmpZmxyMMzMzYmZGwMzAmZZMDMAD2glxox2AyMBYDDMzAMA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 4,
    ["name"] = "Disintegon-sargeras",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMzgZYGmhZGzYMTjZmpZmxyMMzMzYmZGwMzAmZZmZgBYwGsMGN2GQmJAbYgZGMjB",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 5,
    ["name"] = "Fuchur-illidan",
    ["code"] = "CsbBPJc41CfcseY0baneJ1IHrBAAAAAAAAAAAzMzgZYGmZMzMGjZaMzMNjxyMmZmZGzMzAMzAmZZmZgBYwGsMGN2GQmJAbYgZGMMA",
    ["classId"] = 13,
    ["specId"] = 1467,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 1,
    ["name"] = "Romancer-llane",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2MwwMzwMjHAbDDAAMDzMjxwMNmZGAAAYbmZmmxYmZMmBAGzMmZZjFLMMzMTDNbmxihxMDmZYA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_evoker_devastation",
    ["rank"] = 1,
    ["name"] = "Evokes-moon-guard",
    ["code"] = "CEcBPJc41CfcseY0baneJ1IHrxMzYbGmxywMmlZMGmBAAAAAMAAwMDzMmZoGzMzAAAAgZmBmZWGzMGmZbYYWmx2ysMMz2wMMz0I2wMzgZGYYA",
    ["classId"] = 13,
    ["specId"] = 1473,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 1,
    ["name"] = "Dukask-tichondrius",
    ["code"] = "CwQAi6cZM+HWADeySjzG9Lwx8DAAAgZZzYGzwyM2MmZAAAAAAAYZBmYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAglZZaZ2mZZAAgAYYDMzAmGDYAAD",
    ["classId"] = 10,
    ["specId"] = 268,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 2,
    ["name"] = "Tigroll-malganis",
    ["code"] = "CwQAi6cZM+HWADeySjzG9Lwx8DAAAgZZzYGzMWmBmZGDAAAAAAwyCMYmBmhBzgZGzYmthZMzywymttZbGzCAAsMLjlZbmlBAY2mFzMzswwGYmZmhxYADAYA",
    ["classId"] = 10,
    ["specId"] = 268,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 3,
    ["name"] = "Satanics-guldan",
    ["code"] = "CwQAi6cZM+HWADeySjzG9Lwx8DAAAgxyMmhZwMLMzMAAAAAAAssgRMzAzwYxMGzDMzMmZBzMzsMssZZbMzMLAAw2sMtMLzsMAAzys1MzMbmhFwMzMDTzAAAMA",
    ["classId"] = 10,
    ["specId"] = 268,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 1,
    ["name"] = "Kecub-sargeras",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzYMghZZmZ2mxAAAAAAAAAAAALDjmxM2GGwMGmZmZY2GmBLmAA2Mz2YYMzMQAshlZbMNLzSzMzsAMMwMDAjtZAGwA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 2,
    ["name"] = "Clapity-tichondrius",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzYMghZZmZ2mxAAAAAAAAAAAALDzEmhhBMjhZmZGmthZYWmJAgNzsNGGzMDEAbAoZZWamZmFghBmZAglxAGwA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 3,
    ["name"] = "Chizuki-zuljin",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzYMghZZmZ2mxAAAAAAAAAAAALDzEmxywAmxwMzMDz2wMMLzEAwmZ2GDjZmBCgNA0sMLNzMzCwwAzMAwCDYAD",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 4,
    ["name"] = "Sungdripwoo-tichondrius",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzYAMMbzMz2MzAAAAAAAAAAAALDzEmhhBMjhZmZGmthZYWmJAgNzsMGGzMDEAbAoZbWamZmFghBmZAglZAGwA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 1,
    ["name"] = "Fullsmartmw-sargeras",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZGMjZ2MzmtZGbmZ0wM2wgBMbzMmhZbWAz2MBAAAAmlptZbmlZx2MLzyMDIAAGfwMDmBMGYRGzA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 2,
    ["name"] = "Fortunecooky-twisting-nether",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMWGLDsYMzYxMLbLzYGMLLbzMWYGNjZsgBzCMbjZmhZbWAz2IAAAAwsNtMLzsMLWmZZWmZABADGDwMgBGmMmBA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 3,
    ["name"] = "Rebirthstory-illidan",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZGMjZ2MzmtZGbY0MmBMYAz2MjZGzysAmtZCAAAAMLTbz2MLzmtZ2mlZGQAwA+gZGMDYMwykxMA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 4,
    ["name"] = "Meepmonk-kilrogg",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZgFjZGLzMLbLzYgZx2MjNmRzYGLYwsYGz2YmZY2mFMmtRAAAAgZZab2mZbWsMzysMzACAGMmZGMDAAZMDA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_monk_mistweaver",
    ["rank"] = 5,
    ["name"] = "Stankfists-area-52",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZgFjZGLzMLbLzYgZx2MjNmRzYGLYwsYGz2YmZY2mFMmtRAAAAgZZab2mZbWsMzysMzACAGMmZGMDAAZMDA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_deathknight_frost",
    ["rank"] = 1,
    ["name"] = "Creepy-area-52",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMDYmhZMmZYWGzMDbzYmmZMzMDzYYmZGMzMzMDAAAAAAAAAGz2ADYDsMMhMWMmZYmBMAGmZAYgB",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "shuffle_deathknight_frost",
    ["rank"] = 2,
    ["name"] = "Luvgpt-frostmourne",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMDYmZYMzMDzyYmZYbGjmZMzMDzYYmZGMzMzMDAAAAAAAAAGz2sZ2mhxCDLzsNN0MWMmZYmBMAGmZAYgB",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "shuffle_deathknight_frost",
    ["rank"] = 3,
    ["name"] = "Flarkness-dawnbringer",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMDYmhZMzYYWMzMDLzYmmZMzMDzwYmZGMzMzMDAAAAAAAAAGzysZWmhxCDLzsNN0MWMmZYmBMAGmZwMDDM",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "shuffle_deathknight_frost",
    ["rank"] = 4,
    ["name"] = "Lotionman-sargeras",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMDYmZYMzMDzyYmZYbGjmZMzMDzYYmZGMzMzMDAAAAAAAAAGz2sZ2mhxCDLzsNN0MWMmZYmBMAGmZwMDDM",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "shuffle_deathknight_frost",
    ["rank"] = 1,
    ["name"] = "Silènt-tichondrius",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmZMjZGDz2MzMTzmZGzMjBAAAAAAAgZeAmZAwyMmZ2mZGzYAWMLGGyAzGDNWwAmBAmZGzAMzgZMA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 1,
    ["name"] = "Jd-anetheron",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhZGzsMzYxYGzYbsZmFjmYWmhZwwDslBgBgNwmZzMzsMbzMzWDAYmZZbxyMDbsxAbmhZYGmBwMDmZwgRD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 2,
    ["name"] = "Thoryin-tichondrius",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzMLmZGzYbwMLoJmlZYGMYLDADAbgNz2MzAgAAmZW2WsMzwGbjhxmZYGmhZAMzAgBjGA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 3,
    ["name"] = "Trpblitzer-stormrage",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzMLzwYGbjtZmNmmYWmhZwgtMAMAsB2YzMzsMLzMzSDAYmZbbx2MDbsxwYzMMzwwMAmZwMjxgRD",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 4,
    ["name"] = "Memoriesonly-area-52",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzYxMzYGbjtZmFmmYWmhZGGslBgBgNwmZzMzsMLzMzSDAYmZZbxyMDbsxwYzMYGzwMAmZAwAaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 5,
    ["name"] = "Masone-emerald-dream",
    ["code"] = "CEEAVg1HmQqr1Dwlv86ljju8vCAAAYBAMDAwglhBzsMzYZGzYGbjNzsM0EzyMMzwgtMAMAsB2MbmZAQAAzMLbLWmZYjtxwYzMMDzwMAmZAwAaA",
    ["classId"] = 2,
    ["specId"] = 65,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 1,
    ["name"] = "Andreinator-malganis",
    ["code"] = "CIEAVg1HmQqr1Dwlv86ljju8vuZMYWGLzMjZmZZZMzwsMLzYAAAAAAAAgmmZWMjZGGmtAgBMgBbDAAgAMzsst0yMjFzwMAYMDjBAzMAYmBMA",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 1,
    ["name"] = "Gavìon-proudmoore",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQzy2MzsNmZGDAAAAAwMlZZGmZsNYbYmtZMGzMMjN2GGwsMLzMzSzMTbzMbzAA2AMAGjZMDMMsglZmZGGDDG",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 2,
    ["name"] = "Neshaelion-illidan",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsNjZGDAAAAAwoMMMzYbY2GMbzYmxMDzYjthBMLz2Mzs0Mz02Mz2MAgNADgBGmBzYMbYbmZmxMmxgPA",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 3,
    ["name"] = "Pleepo-sargeras",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsMmZmZAAAAAAmpMMMzYbY2GmZbGjxYYGbshBAgMz02Mz2MAgNADAGzwMYGzYDLzghxMGM",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 4,
    ["name"] = "Evnine-illidan",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsMmZmZAAAAAAmpMMMzYbY2GmZbGjxYYGbshBAgMz02Mz2MAgNADAGzwMYGzYDLzghxMGM",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_holy",
    ["rank"] = 5,
    ["name"] = "Melderas-moon-guard",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQzy2MzsNmZmZAAAAAAmpMLzwMjtBbDzsNjxYmhZsxGAmlZZmZWamZabmZbGAwGgBwYmZMDMjhNsMDGGDDG",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 1,
    ["name"] = "Stinkie-malganis",
    ["code"] = "CkQAy0jxIDofkwJmoH7WhvESotMzwMY2MjlZmZmlBAAYmZzyMzsNGAYWWWGDjZxMGzMDbMLMsMAAAMDAAMzMzMzMGjZmhZMzMzMYmZGAgBMA",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 2,
    ["name"] = "Goseilock-tichondrius",
    ["code"] = "CkQAy0jxIDofkwJmoH7WhvESoZmZmZmpZhxCzYWGAAwMzsMbmZWGDAM2WGYATwMsFYYbAAAwAAAYmZMjxYmxMYmZmxwMzMDAYGYA",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 3,
    ["name"] = "Filese-tichondrius",
    ["code"] = "CkQAy0jxIDofkwJmoH7WhvESotMGzMjmtZGLMzMLDAAwMziFzMLzMAwsssMGGziZaMzMslZjhtBAAgZAAgZmZmZmZYMzMMjZmZMYGzAAMgB",
    ["classId"] = 9,
    ["specId"] = 265,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 1,
    ["name"] = "Redfish-tichondrius",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESotMGPwM0sYGLMzMLDAAAAAAwYZZGzMDbGGmZb2ahmxmZmZmtZbmZGGAYGmZMzMYmZmZMzsBAAYmZGjZYbGDYA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 2,
    ["name"] = "Slantsix-tichondrius",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESoxMjZGNbmx2MzYWGAAAAAAgx2yADYAzwWIjNjZGLjZmxMDAMzMzYGgZmxMMzGAAYMzMzMGsNzAMA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 3,
    ["name"] = "Ezav-tichondrius",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESohhZmpZZmZWmZGzyAAAAAAAMW2mxMzwihhZ2mtWoZsZmxYbMjZmZAAzMzYmZGMzwMmZWAAAjZmZMGsMzAMA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 4,
    ["name"] = "Beyourselff-tichondrius",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESotMGzMjmtZGLMzMLDAAAAAAwYZZGzMDbGGmZZ2ahmxixYsNLzMzwAAzMmZmZmBzMzMDzAAAMmxMGzw2MGwA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_demonology",
    ["rank"] = 5,
    ["name"] = "Falco-destromath",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESoZMmZGNLmxCzMzyAAAAAAAMWWmxMzwmhhZWmtWoZsZmZGbjZMzYAAzMDzMzgZmZmZmZAAAGzYGjxYbmBYA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 1,
    ["name"] = "Pxdxtoo-tichondrius",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMzY2GjZGzMzMbzYmZYYAAAAAAAAAAYmZ2GYMzYZGzMmlFTzEwYmZBDhxsNzysxYMWMAAMmhxwMgZmZGNDPA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 2,
    ["name"] = "Sshhaaddooww-tichondrius",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMGWmZMzMwMbzYmZMjZGAAAAAAAAAAzMzyMYmZGLmZmhFmmJGYmZ2wQYMLjlZZxYMWMAAMmhxgBmZmZmJYA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 3,
    ["name"] = "Notatk-tichondrius",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMGWmZMzYwMbzYmZGjZGAAAAAAAAAAmZWmBDzYxMjhFmmpxAMzCGCjZZAGDWAAgxMzMzgBwMzMBD",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 4,
    ["name"] = "Pxdx-tichondrius",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsYY2mZMzMzMjZDmZmZ8AzAAAAAAAAAAYmZ2GjZMzYZYmhlFTzEDmZmZBDhxsNzysxYMWAAgxMjxgBMzMzoZ4BA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 5,
    ["name"] = "Niikmo-tichondrius",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMzwyMjZmBMbzYmZMjZGAAAAAAAAAAzMzyMYmZGLzYmhlFTzEDMzMLYIMmlxyssYMGLGAAGzwYwAzMzMmgB",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 1,
    ["name"] = "Pancakeboi-tichondrius",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAwMmxsMzMmZGYGmZbmZmBAAAwMzsMDGjxixYMLLGzUAMz2MbzMZ2mZ2GgZmBLmZsAoZMjZMYssNYmZG4DA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 2,
    ["name"] = "Holyrizz-tichondrius",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAYzYGzyYmxMjhZYmtZmZGAAAAzYWmBzMGLGzMmlFjZKAmZbmlZmMbzMbDwMzgNzMWA0MMjxAWWGMzMD8BA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_discipline",
    ["rank"] = 1,
    ["name"] = "Notmeanzy-blackhand",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yMMDDAAAAAAAAAAAgBLmxYZmxMzyMDzw2MzYmZGbIzYxMNAzMzAABY2mtlgZjBYmZGMmZmxsxMYmBzgB",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_hunter_survival",
    ["rank"] = 1,
    ["name"] = "Jaywaz-tichondrius",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZb0ssMMDzMNYzYmZMzDsMPAAAAAAAzMzYGmxYGzMMmmBAAAAAAw22MzsYmZmZMmBYmtZYZBzYMjNG",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_hunter_survival",
    ["rank"] = 2,
    ["name"] = "Valcorex-illidan",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZb0stMMDzMNYzYmZMeglZAAAAAAYGGzssMjxMMGzoZAAAAADAgltZmHYxMzMzMMzAmZbG2WwMGzMbMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_hunter_survival",
    ["rank"] = 3,
    ["name"] = "Bangalash-tichondrius",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMDzMbjmtlhZwMNYzMzMjZeglZAAAAAAYGPwYgxYmZGziRzAAAAAGAAbLzMPwmZmZMzYmBMjZYZBzYMjFG",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_hunter_survival",
    ["rank"] = 4,
    ["name"] = "Aydenxd-stormrage",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZb0stMMDzMNYxMzMjxsMDAAAAAAzwYmllZMMzDMYGNDAAAAYAAstMzMbmZmxMMzAmZbG2WwMGzYjPA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_hunter_survival",
    ["rank"] = 5,
    ["name"] = "Boomsticklol-tichondrius",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMDzMbjmtlhZwMNYzMzMjxDsMDAAAAAAz4BGzgxYmZGziRzAAAAAGAAbLzMzmZmZMDzMgZMDLLYGjZswA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 1,
    ["name"] = "Noxidwehttam-illidan",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORxMjZmZMzMzMjZmJDDAAAAAAwsYMmZMzMbzMjlZbMjlBzYbmlZWmlZmZW2mlppZmZGzYBAAAAAABYmZmBDABAAG",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 2,
    ["name"] = "Rytes-moon-guard",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORxMjZmZYMzMjxMMmZAAAAAAAzixsNzYmZ2mZGsNjZ2GMjtxyMLzyMzM2mlxYmZmxM2AAAAAAAAmZmBDAAAAD",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 3,
    ["name"] = "Nemos-emerald-dream",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMDjxMjxMMmZAAAAAAAzyMmtZGzMz2MGbz28AzMbDmx2MbzsMbjZssNLDmZmZMjFAAAAAAAwMzMDAAAAwA",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 4,
    ["name"] = "Lem-wyrmrest-accord",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORZGMzMzmxMzMmZmMmZAAAAAAAzyDMmtZYmZ2mZGbz28AzwYYsMw2sYGDzmmGzMjhNAAAAAAEAMzgBgAAAD",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 5,
    ["name"] = "Azrethec-wyrmrest-accord",
    ["code"] = "CEkAG5bbocFKcv+yIq8fPd6ORxgZmZYMzMzMzMZYGAAAAAAwsYMmZMzMbzMzsMbzMjlBzYZmlZwwYZjJZMzYGLAAAAAAIAzMADABAAG",
    ["classId"] = 12,
    ["specId"] = 577,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 1,
    ["name"] = "Onimetsu-area-52",
    ["code"] = "CUkAG5bbocFKcv+yIq8fPd6ORBAYMzMjhZkZmBWMjZwMjZGz8AzMzYYmtZGbzMjxYGAAAAAAABMzM2AAAAwAzMzMzSbzMzAADAAAgB",
    ["classId"] = 12,
    ["specId"] = 581,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 1,
    ["name"] = "Bigeartuutu-tichondrius",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBAWMmZmZmZmxwMAAAAAAAegxsNYGAAAAAAAAmxMMmZmZmZmZGzsYGjFW2YmZmZzyMzMAGGAAmxgxMA",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 2,
    ["name"] = "Giteff-gundrak",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBA2MmZmZmZmxwMAAAAAAAbzYMYGAAAAAAAAmxgxMzMzMzMzYmFzYswyGzMzML2mZmBwwMzsMzMmtZ2mxgxMA",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 3,
    ["name"] = "Gameoverdh-tichondrius",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBAMzMmZMzMjhZAAAAAAAWegxYMmBAAAAAAAgZMDzDMzMzMzMzwMLzMGLaZjZmZmt2mZmBwMMzsMGNmZzYwYGA",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 4,
    ["name"] = "Ouru-area-52",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBAWmZmZmZmZmxwMAAAAAAAMGDmBAAAAAAAgZMDzDMzMzMzMzwMLzMGLssxMzMzmtZmZAMjZmZZmZMLzsZYYMD",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "shuffle_demonhunter_havoc",
    ["rank"] = 5,
    ["name"] = "Celedan-area-52",
    ["code"] = "CgcBG5bbocFKcv+yIq8fPd6ORBA2MmZmxMzMGzMAAAAAAAegxsNYGAAAAAAAAmxMMmZmZmZmZGzsYGjFtsxMzMzWbzMzAYYAIwMGMmB",
    ["classId"] = 0,
    ["specId"] = 1480,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 1,
    ["name"] = "Nosone-illidan",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESotMGzMjmNzYhZmZZAAAAAAAGLLzYmZYzwwMbzWL0M2MmZsNmZmZmBAmZmZYmZwMzMzYMAAAzMzMjxMsNzA8AA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 2,
    ["name"] = "Ucanttouchme-malganis",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESoZmhZGNbmx2MzYWGAAAAAAgx2yMmZGWMMMzys0CNjNjZGLjZmxMDAMzMzYmZGMzYmZGzGAAYMzMjxgtZGgB",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 3,
    ["name"] = "Dichtor-illidan",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESoZmZegZGNbmx2MzYWGAAAAAAgxyyADYAzwSIjNjZGLz2MzwMAwMzMzMDwMzMGmBAAYMzMzMGsNDgB",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 4,
    ["name"] = "Shadoowbane-stormrage",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESoZMmZGNbzMWYGz2AAAAAAAMWWGYADYGWCZsZMzYb2mZGmBAmZmxMDwMzMzMmBAAYmZmZMGYGDYA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 5,
    ["name"] = "Minihdp-ragnaros",
    ["code"] = "CoQAy0jxIDofkwJmoH7WhvESoZMmZGNbzMWYmZWGAAAAAAgxyyMmZG2MMMzys1CNjNjZGbjZmZYAgZmZmxMzgZmZmZGDAAAzYGjZYbMDYA",
    ["classId"] = 9,
    ["specId"] = 266,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 1,
    ["name"] = "Diábolical-sargeras",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESotMGzMjmtZGLMzMLz2wYWmxstYGAAMzMmZmFbYmZMzyyoZmhlhlZpxGDAAMAzsBAMzAzMzYAAAYGzAAwYYA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 2,
    ["name"] = "Destosterone-hyjal",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESotMmZmZ0sNzYjZmZZMMzsMjZbxMAAYMjZmZxGmZGzssMamZYZYZ2asxAAADwYDAYmBmZmxAAAwMGAAMzwA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 3,
    ["name"] = "Drexia-tichondrius",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESotMz4BmZmmNzYhZmZZWYY2MzstYGAAMzMmZmFbYmZMzyyoZmhlhlZrxGDAAMGwsBAMzgZmxYAAAYGzAAw8ADD",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 4,
    ["name"] = "Br-burning-blade",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESotMGPwMjmlZGLMzMLzCzYWmxstYGAAMzMmZmFbYmZMzy2oZmhthlZrxCDAAMGYsBgZmZGMzMzYAAAYGzAAwYYA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "shuffle_warlock_destruction",
    ["rank"] = 5,
    ["name"] = "Voidchaos-whisperwind",
    ["code"] = "CsQAy0jxIDofkwJmoH7WhvESoZMMzoZbmxmZmZWmFmxsNjZbxMAAYmZMzML2wMzYmllRzMDbDLzWjNGAAYAmZDAYmBzMzMzAAAwMmBAgxwA",
    ["classId"] = 9,
    ["specId"] = 267,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 1,
    ["name"] = "Hachu-moon-guard",
    ["code"] = "CwQAi6cZM+HWADeySjzG9Lwx8DAAAgZZzYGzwyM2MmZMAAAAAAALLgYmBmhBzgZmZGzsNMjZWGW2ssNbzYWAAglZZaZ2mZZAAgAYYDMzAmGDYAAD",
    ["classId"] = 10,
    ["specId"] = 268,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 1,
    ["name"] = "Jaw-illidan",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8bmZMwMjZbGzyMGAAAAAAAAAAAYZYEmZ2GGYBzYmhZMbzCDzyMBAsZmNzYGzMDEAbYZWGTz2s0MzMLAMDMzYAYZAjZmZxHA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 2,
    ["name"] = "Hdg-moon-guard",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzYMgBLzMz2MGAAAAAAAAAAAYZYmwMMMgZMMzMzwshZYWmJAgNzsNzwYmZgAYzMLzyYaWmlmZmZDYMDMzMDwYZAMzMbG",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 3,
    ["name"] = "Nate-frostmourne",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzMjBMYbmZWmxAAAAAAAAAAAALDjwMzGGDGmxMDzYWmFGmlZCAYzMLjhZmZGIA2Mz2sMmmtZpZmZWAGzAzMzAwyAGzMzmPA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 4,
    ["name"] = "Facepalmin-spirestone",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzMjBMYbmZ2mBAAAAAAAAAAAYbYEmZ2wYYZYGzMzMMbDGmlZCAYzMLzMMmZGIA2MzysMmmtZpZmZWAGGYmZGAWGAzMzmB",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 5,
    ["name"] = "Keycogx-illidan",
    ["code"] = "C0QAi6cZM+HWADeySjzG9Lwx8PzMjBMYZmx2MGAAAAAAAAAAAYbYEmZ2wAGmxMzMDz2gZMLzEAwmZWGjZMzMQAsZmNGTz2s0MzMLADDMzYAYZAjZmZzA",
    ["classId"] = 10,
    ["specId"] = 269,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 1,
    ["name"] = "Skydre-illidan",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMWGLDL2MmZsgtllZMDzsttMzYhx0MmBMYwgZmZGmNGDzyMBAAAAQAWsMzysNzACAgxAMDYMwiMmBA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_monk_windwalker",
    ["rank"] = 2,
    ["name"] = "Raires-tichondrius",
    ["code"] = "C4QAi6cZM+HWADeySjzG9Lwx8DAAAAAAAgxMzyYZMbWMmZsZAjZ2Mz2y2MjNmRzYGLYwswY2GzMDz2sgxsNCAAAAMLTbzmZbWsMzysMzACAGMmZGMDAwiMmBA",
    ["classId"] = 10,
    ["specId"] = 270,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 1,
    ["name"] = "Ilh-sargeras",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmZmFzMmZGAAAghphZGzMbmZmZGzwMDAAAAgxyMDImxy2sYmlhNDDzMz0GNzgNwMwYGsMzygZmZGAmBGA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 2,
    ["name"] = "Jessicãjin-illidan",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmZmlZmZGDAAAghphZmxMLMzMDzwMDAAAAgxiZgtMzYZbWMz2wmhhZmZahmZGWAmxyMLjBzsNYmBAghB",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 3,
    ["name"] = "Río-area-52",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4DzMzsNzMzYAAAAMMhxMzYxMzMDzYmZAAAAAMWMDslZGLbziZ2G2MMMzMTL0MDWAmxiZZMbMz2gZmZGAmxwA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 4,
    ["name"] = "Isnlonely-tichondrius",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmZmlZmZGDAAAghxwMzYmFmZmhZYmBAAAAwYxMwGmxy2sYmthNDDzMzYDzMDLAzYZmlxsxMbDmZAAYYA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 5,
    ["name"] = "Braxxinn-zuljin",
    ["code"] = "CcEAjLzRlq54bI5v+r8Sr9Xw4jZmZmFzMzMDAAAghphZGmZZxMzMDDzMAAAAAGLPwMgYGLbziZ2G2MMMzMTb0MDWAmxyMLzMbMjBzMzMAYMMA",
    ["classId"] = 1,
    ["specId"] = 71,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 1,
    ["name"] = "Urdem-moon-guard",
    ["code"] = "CgEAjLzRlq54bI5v+r8Sr9Xw4DAAAAAAAjhZmZmZhZmZMYmZMjZmZ2mZmZMmlxMzAAAYmttxCbWWMjxMzwwsxMjFAzsYsMAYmBYGGGDDG",
    ["classId"] = 1,
    ["specId"] = 72,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 1,
    ["name"] = "Ngu-eldrethalas",
    ["code"] = "CkEAjLzRlq54bI5v+r8Sr9Xw4nBAAGzYmZmZmxsZmZZYMmpxMGWGzMzwMmZAAAAwyAwMGAYzMG2IDMDL0YmFGzMzMY2GAgZGAwAMA",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "shuffle_warrior_arms",
    ["rank"] = 2,
    ["name"] = "Todory-moon-guard",
    ["code"] = "CkEAjLzRlq54bI5v+r8Sr9Xw43yAAAzMzYmZGzMzmxsMjxYmGmZYZMzMDzYmBAAAALDAzYAGYDWWMaMDgZLmZDmxMDmtBAzMAAMAD",
    ["classId"] = 1,
    ["specId"] = 73,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 1,
    ["name"] = "Dapperspud-frostmourne",
    ["code"] = "C4DAMhlVtghLZL4RZzExaQoBYNzwMLzMzswDMzQzMGAAAGAAEwMzMLLzMxCAAbzYmZMbmlZmZMzYMMzMjFmZmxMAADAAgZWAAzAghB",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 2,
    ["name"] = "Jüker-stormrage",
    ["code"] = "C4DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZzyDMzQzwAAAwAAgAmZmZZZmJWAAYZMzMjxilZmZMzMjxMzMjFmZGmBAYAAAMzCAMGA8BM",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 1,
    ["name"] = "Ozaki-tichondrius",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZzmZGMDzAAAYmlZMzsNLzMjZbZZGAgNzMzsNMmZWAAAAAgFmZmBAAGmZGmhZWmHAwMDMGDDzwA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 2,
    ["name"] = "Polyru-tichondrius",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNstMzyMzMLWMzIzDwMAAAGAwMz0sssMDAwmZGz2wYmZBAAAAAWMzMzAAAjZMDzMmZZeAAzMkZGDYGG",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 1,
    ["name"] = "Oldboy-moon-guard",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzML2mZmYeAmZmZmZWMzMmZMzsMTzMbzCAYmZmllZm2AAgFAAAgNA2WGzMzALGjZmlFAAAmZBYGGAgB",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 2,
    ["name"] = "Yesa-tichondrius",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzML2mZmYeAmZmZmZWMzMmZMzsMTzMbzCAYmZmllZm2AAgFAAAgNA2WGzMzALGjZmlFAAAmZBYGGAgB",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 3,
    ["name"] = "Fujikaze-kelthuzad",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzMLzyDMzEDmZmZmZYmZMzYmZZmmZWmFAwMzMLLzMtBAALAAAAbAssMmZmB2MGzMWAAAYmNgZYMgZwA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 4,
    ["name"] = "Wakeenfnx-tichondrius",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzMb2mZmYeAmZmZmZWMzMmZMzsMTzMbzCAYmZmllZm2AAgFAAAgNA2WGzMzALGjZmlFAAAmZBYGGAgB",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_frost",
    ["rank"] = 5,
    ["name"] = "Abrua-bloodhoof",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNzwYZmZmFmZmYGmZmZmZWMzMMjZgAAAzMzssMz0GAAsAAAAsAw22YmZGMbDjZGbAAAMzGwMMGwMYA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 1,
    ["name"] = "Vinipriest-moon-guard",
    ["code"] = "CAQA4VPTJ8eQb8/qEm8PyGu4yADsMzwyMj5BGzMMbzsNzMjxMDAAAAAAAAAgZmZZGmxMjlZMzwCTzEDmZmZDDhxsMzysxYMWAAgh5BMGMgZmZmJ4BA",
    ["classId"] = 5,
    ["specId"] = 256,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 1,
    ["name"] = "Nïkkï-sargeras",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4ywYAAAAAAAmxMmlZmxMDYGmZbmZmBAAAwMzsNDGjxiZGDLLGzUAMz2MbzMZ2mZ2GgZmBLMzsAoZMjZMYssNYmZG4DA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 2,
    ["name"] = "Qtfemboi-tichondrius",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAwMmxsMzMmZAzwMbzMzMAAAAmZmtZwYMWMzYYZxYmCgZ2wQYMbDwYgFzMzCgmxMmxgBwMzMwHA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 3,
    ["name"] = "Xiuni-shadowmoon",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4ywYAAAAAAAmxMmlZmxMDYGmZbmZmBAAAwMzsMDGjxiZGDLLGzUAMz2MbzMZ2mZ2GgZmBLMzsAoZMjZMYssNYmZG4DA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 4,
    ["name"] = "Astroverse-tichondrius",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAwMzMsMzMmZAzwMbzMzMAAAAmZmlZwYMWMzMjZZxYmCgZ2wQYMbDwYgFzMzCgmhhxgBwMzMwHA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 5,
    ["name"] = "Thedude-spirestone",
    ["code"] = "CEQA4VPTJ8eQb8/qEm8PyGu4yADAAAAAAwYmxsMzMmZYYGmZbmZmBAAAwMzsMDGmxyMmZYZxYmCgZWmZZmJz2MzyAMzMYxMzAQzYGmZwYZbwMzMwHA",
    ["classId"] = 5,
    ["specId"] = 257,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 1,
    ["name"] = "Eyefloaties-area-52",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yADzAAAAAAAAAAAAMYxMmZZmxMz2MGzM2mxYmZGbIzYZZmGgZmZwMLmRzmBz2stkxMbMAzMzgxMzMmNGbbzMDmBD",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_priest_holy",
    ["rank"] = 2,
    ["name"] = "Bibleblak-stormrage",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yMMjZGAAAAAAAAAAAghZxMGLzMMzyMDzMz2MYMzYzIzYxMNGYmZGMziZ0sZwsNbbZMzCDwMDYMjZMbjZ2WGgZwA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 1,
    ["name"] = "Yaya-kargath",
    ["code"] = "C4DAMhlVtghLZL4RZzExaQoBYNssMzyMzML2MzQzMmBAAwAAGzklFzMzMzy2MTsAAwyMmZGjFLzMzYmZGjZmZGLMzMjZAAGAAAzsgZGgBADA",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 1,
    ["name"] = "Talibandzx-sargeras",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNzwMLzMzsgZGMzYAAAYAAzMjZZZZGAgNzMjtxMzMWAAAAAgFzMzMDAAGzwYmZmZ2GAmZAGjBzwA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 2,
    ["name"] = "Goreckiboi-tichondrius",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZMb2MzIzwMAAAGAwMz0sssMDAwmZGz2wYmZBAAAAAWMzMzAAADzMDzwMLzAYmhMmZYYGG",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 3,
    ["name"] = "Smuky-stormrage",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNstMzyMzMb2MzIzwMAAAGAwMz0stsNDAwmZG2GzMzYBAAAAAWMzMzAAAjZMDzMzMLzAYmhMGDYGG",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 4,
    ["name"] = "Melionas-tichondrius",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZDzMyMMDAAgZWmxMz2sMzMNbLLzAAsZmZmthxMzCAAAAAsYmZmBAAGmZGmhZWmBmZmZIjBGmhB",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 5,
    ["name"] = "Blaysen-tichondrius",
    ["code"] = "C8DAMhlVtghLZL4RZzExaQoBYNmllZWmZmZx2MzIDmBAAwAAmZmmtltZAA2MzY2GGzMLAAAAAwiZmZGAAYYMDzMmZZeAAzMkBDDzwA",
    ["classId"] = 8,
    ["specId"] = 63,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 1,
    ["name"] = "Vìego-moon-guard",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNDGLzMzsMmZmYMmZmZmZWMzMMjZgAAAzMzssMz0GAAsAAAAsBw22YmZmHgZbYMzYDAAgZ2AmhxAmBD",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 2,
    ["name"] = "Dunkyb-tichondrius",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZxmZmYGmZmZmZWMzMmZMzsMTzMLzCAYmZmllZm2AAgFAAAgNA2WGzMDYxYMzssAAAwMLAzwYAgB",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 3,
    ["name"] = "Icelanceetko-kelthuzad",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNGLzsMjZWGPwMTMDzMzMzMbmZmZGmBCAAMzMzyyMTbAAwCAAAwGAbLjZmZAGjZGbAAAMzGwMMGwMYA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 4,
    ["name"] = "Ipdfwu-proudmoore",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYZGGLzMzsMmZmYmxMzMzMziZmZMjZmlZamZZWAAzMzssMz0GAAAAAAYBgtlxMzMY2GGzwCAAAzsBMDjBMDGA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_mage_fire",
    ["rank"] = 5,
    ["name"] = "Zoki-emerald-dream",
    ["code"] = "CAEAMhlVtghLZL4RZzExaQoBYNstMzyMzMLWMzEzwMzMzMziZmxMjZmlZamZbWAAzMzssMz0GAAsAAAAsBw2yYmZGYxYMzYBAAgZWAmhxAMYA",
    ["classId"] = 8,
    ["specId"] = 64,
  },
  {
    ["bracket"] = "shuffle_rogue_subtlety",
    ["rank"] = 1,
    ["name"] = "Nahj-tichondrius",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbMmZMDmZmZmlxsNMzssMMYmxAmxAAAAYGMwsMjZbGGLMYmtpFaZ2YmBzMzgZmB",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "shuffle_rogue_subtlety",
    ["rank"] = 2,
    ["name"] = "Mharcoz-stormrage",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgx2MAAAAAwsMGLTMbbjxMjZwDMzMzYMbjZGbbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "shuffle_rogue_subtlety",
    ["rank"] = 3,
    ["name"] = "Zurza-tichondrius",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsMmZssMmBzMGwMGAAAAzwMsYWmxsNDjFG2mZbahWmNmZYmZmBzYA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "shuffle_rogue_subtlety",
    ["rank"] = 4,
    ["name"] = "Mimimimimimx-sargeras",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbmZmZMDMzMzsMmthZssMMDzMGwMGAAAAzwMsYWmxsNDjFGWmZbahWmNmZYmZmBzYA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "shuffle_rogue_subtlety",
    ["rank"] = 5,
    ["name"] = "Tiesto-illidan",
    ["code"] = "CUQAByFP3pExAEG41/8+e6b8fDgZ2mBAAAAAmtZmZZiZZbmxMjZgZmZmlxsNmZssMzMYmxAmxAAAAwwMsZWmxsNDjNGWmZbahWmNmZYmZmBzYA",
    ["classId"] = 4,
    ["specId"] = 261,
  },
  {
    ["bracket"] = "shuffle_shaman_enhancement",
    ["rank"] = 1,
    ["name"] = "Literalpaper-stormrage",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZZGGjllZswMzGbmZmhZ2YGAADzYGzMNmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "shuffle_shaman_enhancement",
    ["rank"] = 2,
    ["name"] = "Earthquake-sargeras",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjFmZ2GLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "shuffle_shaman_enhancement",
    ["rank"] = 3,
    ["name"] = "Tech-laughing-skull",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjlxMzGLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "shuffle_shaman_enhancement",
    ["rank"] = 4,
    ["name"] = "Laabuubuu-malganis",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjlxMzGLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "shuffle_shaman_enhancement",
    ["rank"] = 5,
    ["name"] = "Musclebrain-tichondrius",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMzgZmZmZmZmZGzAAAAAAAAAALYbZGzMbba22GmhZmGsAwsNYM2WmxyYMGLmZmZMz2wAAMDzMDzMBmZwgxHA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "shuffle_druid_balance",
    ["rank"] = 1,
    ["name"] = "Wakeenfiendx-tichondrius",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMbwgZbmlZMjZGsMjZmZwGGAM22mx22Mbz2MNzsMTAAAA2YmZmBbGzYMDgZGAsMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "shuffle_druid_balance",
    ["rank"] = 2,
    ["name"] = "Jbz-balnazzar",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMLNjxMDwsNzMzMbmBMLjlZMjZGzsMjZmZwGGAM2WM22mZzyMNzsMTAAAA2Mz8AzMYzYGjZAMzgZGYA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "shuffle_druid_balance",
    ["rank"] = 3,
    ["name"] = "Kdiz-tichondrius",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMbmBmZbmlZ2mxMjxixMzMYDDAGbLGbbzsZZmmZWmJAAAAbmZegxgNjZMGAmZwMDMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "shuffle_druid_balance",
    ["rank"] = 4,
    ["name"] = "Supatease-tichondrius",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWGlZpZMmZAmNzMzMLwgZbmlZMjZGjlZMmZwGGAM22mx22Mbz2MNzsMTAAAA2YmZmBbGzYMDgZGAsMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "shuffle_druid_balance",
    ["rank"] = 5,
    ["name"] = "Fredagn-illidan",
    ["code"] = "CYGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAAAAAAWoMLNjxMD8AmtZmZmZBYmZbsMjZMzsxyMmZmBbYAwYZbmZbbmtZbmmZWmJAAAAbmZmZGsZYMGAmZwMDMA",
    ["classId"] = 11,
    ["specId"] = 102,
  },
  {
    ["bracket"] = "shuffle_hunter_beastmastery",
    ["rank"] = 1,
    ["name"] = "Nullpointerx-tichondrius",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcYxsMjZmhFDLMzMLGaGbAAYmZWGzsYGmxMDDzMGmxMzMGzgZGzMzA0MAAAAAgZAAAYmxMDzMzsgsMWmZBsYA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_beastmastery",
    ["rank"] = 2,
    ["name"] = "Snowmìxy-tichondrius",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcAMmxwCsAzwQDbAAYGz2YmFzwMmZY8AzMGmxMzwYGLzMjZmZMMaGAAAAAwMAAAMDzMgZ2QWwMLgND",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_beastmastery",
    ["rank"] = 3,
    ["name"] = "Blazeybill-frostmourne",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcAMmxwCsAzwQDbAAYGz2YmFzwMmZY8AzMGmxMzwYGLmZMzMjZ5BoZAAAAAAzAAAwMMzAmZDZBzsA2MA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_beastmastery",
    ["rank"] = 4,
    ["name"] = "Lilprimary-tichondrius",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcYzsMjZmhFDbMzMbGaGbAAYGz2YGmhZMzwMPwMjhZMzMMmZZZmZMzMDMaGAAAAAwMAAAMDzMMzMzGyCmZBsYA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_beastmastery",
    ["rank"] = 5,
    ["name"] = "Clavìcular-area-52",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcAMmxwCsAzwQDbAAYGz2YmFzwMmZY8AzMGmxMzwYGLzMjZmZMMaGAAAAAwMAAAMDzMgZ2QWwMLgND",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_beastmastery",
    ["rank"] = 1,
    ["name"] = "Ttcpartyone-proudmoore",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZZ0ssMMDzMNYzMzMjxDsMDAAAAAAzMzYGLGjZmZgRzAAAAAGAALbzMziZmZMDzMgZ2mhtFYMmxGD",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 1,
    ["name"] = "Equinoxpal-sargeras",
    ["code"] = "CIEAVg1HmQqr1Dwlv86ljju8vuNjBzyYZMjZmZZZMzwsMLzYAAGAAAAAA00MzyMjZGGegt2AwADYGsNAAwMTbzMbzMzsst0yMjFzgBAMDjBAzMbzAMzAG",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 2,
    ["name"] = "Hewasright-sargeras",
    ["code"] = "CIEAVg1HmQqr1Dwlv86ljju8vuNj5BYWmZZMjZmxyYmhZZMjBAYAAAAAAgxMDzwMMMbAgBMgBbDAAMzYbmZZGAgNzwMAYMDjBAYZGwMzAG",
    ["classId"] = 2,
    ["specId"] = 66,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 1,
    ["name"] = "Claudinhogdx-nemesis",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQzyyMzsNmZGDAAAAAwMlZZGmhtZYbYmlZ8AGzMMjN2GAmFbDzSzMTLzMbzAA2AMMwMmZYgZMshlZmZGGDDG",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 2,
    ["name"] = "Vânguards-tichondrius",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQz22MzsNmZGDAAAAAwMlZZGmhthZbwsMjHwYmhZsx2AwsMbjZWyMTbzMbzAA2AMAGjZYGMjxshlZGzwYYwA",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 3,
    ["name"] = "Clump-tichondrius",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQzy2MzsNzMzMAAAAAAmpMLzwMzsMYbwsNjxYmhZsxGAmlZbmZWamZabmZbGAwGgBwYMz2AmxYWwyMzMDjhBD",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 4,
    ["name"] = "Ðazuu-illidan",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAMaW2mZmlxMzMDAAAAAwMlxMMzYbY2GmZbGjxYYGbsBAAkZm2mZ2mBAsBYAwYGGYGzYDLzghxMGM",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_paladin_retribution",
    ["rank"] = 5,
    ["name"] = "Divïne-stormrage",
    ["code"] = "CYEAVg1HmQqr1Dwlv86ljju8vCAAAAAQzy2MzsNzMzYAAAAAAmpMmhZGbzY2GmZbGjxDYwYhlBgZb2mZmtmZmWmZ2mBAsBYAMYGjBDzMbYZGMMGGM",
    ["classId"] = 2,
    ["specId"] = 70,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 1,
    ["name"] = "Lnetrapx-ghostlands",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcAMmxwCsAzwghNAAMjZZMziZYGmhZmZGDzwMzYMzyyMzYmZGYYGAAAAAwMAAAMDzMgZ2AwMLgND",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 2,
    ["name"] = "Pelorus-frostmourne",
    ["code"] = "C0PAo4YcvOcqUdzB9zV+NhSAcYxsNjZmhFDLwMM0M2AAwMGjZWMDzYmhxMzYMzwMDjZsYmxMzMwoZAAAAAAzAAAwMjZGwMLILDzsA2MA",
    ["classId"] = 3,
    ["specId"] = 253,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 1,
    ["name"] = "Jax-fenris",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZWGDjZMTjlBkZY2AAAAAAAAAmxDMmxixMzMGjZ0MmZG2W2MmhZmxYmZbMzsMMDAAwMMzAwMstgZAWGG",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 2,
    ["name"] = "Saxs-illidan",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZWGDjZMTjtBkZY2AAAAAAAAAmBmxixMzMPwYMjmZmZG2W2MmhZmxYmZbMzsMMDAAwMMzAwMstgZA2GG",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 3,
    ["name"] = "Flamavan-tichondrius",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZWGDjZMTjlZGWyMMbAAAAAAAAAzYYYxYmZmHYMGaGDmZbhZmhZmxsNzsxMzywMAAAzMmZmZmBzM2WwMALYA",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 4,
    ["name"] = "Sharktism-illidan",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcwCjBmxoxyAyMYDAAAAAAAAYGMzYZGPwMzMDGaGjZmZbZzMzMMzM2mxyYMLDzAAAMzYmBgZGbLYGgNM",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 5,
    ["name"] = "Eazymøney-azralon",
    ["code"] = "C4PAo4YcvOcqUdzB9zV+NhSAcYZZMGGzYmGLjhtMD2AAAAAAAAAmhxMLLzYGzMjhRzYMzMbLbmZmhZG2mx2YMLDzAAAMDzMMzgZGbLsMDghB",
    ["classId"] = 3,
    ["specId"] = 254,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 1,
    ["name"] = "Sax-kiljaeden",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMDzMbDzy2wMYGD2MzMzY8ALzAAAAAAwMegxMWmxwMPwgZYGAAAAwAAYbbm5BWMzMjZYmBMjZYZBzYMzsxA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 2,
    ["name"] = "Jaxh-tichondrius",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMgxMG2IbwMM0gFjZmx4BWmBAAAAAgZYMzyyMGzMGMjmBAAAAMAAWWmZmFzMzYGmZAzsBWwMGzMbMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_hunter_marksmanship",
    ["rank"] = 3,
    ["name"] = "Uh-moon-guard",
    ["code"] = "C8PAo4YcvOcqUdzB9zV+NhSAcMWwMzYmZb0stMMDzMNYzMzMjhlZAAAAAAYGzYmllZ8AMjBzoZAAAAADAgltZmHYxMzMzMMzAmZbG2WwMGzMLMA",
    ["classId"] = 3,
    ["specId"] = 255,
  },
  {
    ["bracket"] = "shuffle_rogue_outlaw",
    ["rank"] = 1,
    ["name"] = "Xygg-barthilas",
    ["code"] = "CQQAByFP3pExAEG41/8+e6b8fDgZYwYGmZbmZmZGPgZZxMzMLTbD2mBAAAAAYZZmZMzMzMzYmZMAAAAmhBGMbzmZmZ0MzGzGLbTLswAMzMzMwA",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "shuffle_rogue_outlaw",
    ["rank"] = 2,
    ["name"] = "Ellaszun-bonechewer",
    ["code"] = "CQQAByFP3pExAEG41/8+e6b8fDgZYwYGmZbmZmZGPgZZxMzMbTbD2mBAAAAAYZZmZmZmZmZGzMjBAAAwMAGMbzmZmZ0MzGzGLbTLswAgZmBG",
    ["classId"] = 4,
    ["specId"] = 260,
  },
  {
    ["bracket"] = "shuffle_priest_shadow",
    ["rank"] = 1,
    ["name"] = "Ophiuchus-jubeithos",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yMDjBAAAAAAAAAAAADLzMGLzMmZ2mZYmx2wYmZGLjJDLMNGYmZGYWY0sZwsNbLZMzGDwYmBjZmZMLjZwMDmBD",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_priest_shadow",
    ["rank"] = 2,
    ["name"] = "Jbz-altar-of-storms",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yYYMGAAAAAAAAAAAADLzMmZZmxMz2MDjZ2mZGzMzYhJDLLmGgZmZwMLmRzmBz2stkxMbMAjxgxMjxsMzYbZmZwMYA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_priest_shadow",
    ["rank"] = 3,
    ["name"] = "Peterlongrod-malganis",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yMMjZAAAAAAAAAAAAMYxMGLzMmZ2mZYmZMzMmZmxCTGWWMNGYmZGMziZ0sZwsNLLZMzCDwYMYMzDMjZZM22GgZwA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_priest_shadow",
    ["rank"] = 4,
    ["name"] = "Wizkxhmt-tichondrius",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yYYMGAAAAAAAAAAAADLzMmZZmxY2mZGzM2mxYmZGLMZYZx0AMzMDmZxMa2MY2mllMmZjBYMGMmZmxsMmZbZmZwMYA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_priest_shadow",
    ["rank"] = 5,
    ["name"] = "Voidcrafter-frostmourne",
    ["code"] = "CIQA4VPTJ8eQb8/qEm8PyGu4yYYMGAAAAAAAAAAAADLzMGLzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDmZxMa2MY2mtlMmZjBYMzgxMjxsMmZbZmZwMYA",
    ["classId"] = 5,
    ["specId"] = 258,
  },
  {
    ["bracket"] = "shuffle_evoker_preservation",
    ["rank"] = 1,
    ["name"] = "Hyttzdrag-hakkar",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2MwwMzwMjHAbDDAAMDzMjxwMNmZGAAAYbmZmmxYmZMmBAGzMmZZjFLMMzMTDNbmxihxMDmZYA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_evoker_preservation",
    ["rank"] = 2,
    ["name"] = "Jerrzi-illidan",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ22GYYmZwMzgthBAAmhZmxYMzEzDMDAAAsNzMTzgZmZZMDAMmZMzyGLWYYmZmGa2gNDjZGMzwA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_evoker_preservation",
    ["rank"] = 3,
    ["name"] = "Eyjes-stormrage",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2MwwMzgZMYbYAAgZGzMjxYmJGzAAAAbzMz0MYmZWGzAAwYGbsADMjGaYGLwYmBgB",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_evoker_preservation",
    ["rank"] = 4,
    ["name"] = "Halcyonxz-tichondrius",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAGzMz22ADzMDGmhtZMAAMzMMzMGDzEmZAAAgtZmZaGMzMLjZAAYMjNWgBmRDNYsAjZGAGA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_evoker_preservation",
    ["rank"] = 5,
    ["name"] = "Boa-moon-guard",
    ["code"] = "CwbBPJc41CfcseY0baneJ1IHrBAAAAAmZmZ2WGYYmZwMGsNMAAYmhZmxYYmGzMDAAAsNzMTzgZmZZMAgxMjZW2YxCDzMz0QzGjFDjZGMzMGA",
    ["classId"] = 13,
    ["specId"] = 1468,
  },
  {
    ["bracket"] = "shuffle_rogue_assassination",
    ["rank"] = 1,
    ["name"] = "Sanira-illidan",
    ["code"] = "CMQAByFP3pExAEG41/8+e6b8fPzMjZzMAAAAAAmtZMbzAAAAAAaZZYGmZMmZmZ2mZZmBzMzMYGzMzMDD2mZbswYGzSjZZbYy2ww2MsNzgZGYA",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "shuffle_rogue_assassination",
    ["rank"] = 2,
    ["name"] = "Ivanrah-zuljin",
    ["code"] = "CMQAByFP3pExAEG41/8+e6b8fPzYmZbmhBAAAAAmlBbzAAAAAAabbmZmZYMMjZ2mZbYmZmZmxDMDmZmZGDMwCMjRjZBktBsZstAMzMzA",
    ["classId"] = 4,
    ["specId"] = 259,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 1,
    ["name"] = "Zanantu-area-52",
    ["code"] = "CoPASnrjTdwaLTX9NnLQoJJXfwMzyMzwMmZmhZZmZmmZxMjxMGAAAAwMzMzMzMDzYMAYMzMzAAAYMbDMglgthJwwCgZYAAYmBwgB",
    ["classId"] = 6,
    ["specId"] = 250,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 1,
    ["name"] = "Flarkness-dawnbringer",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMDYmhZMzYYWMzMDLzYmmZMzMDzwYmZGMzMzMDAAAAAAAAAGzysZWmhxCDLzsNN0MWMmZYmBMAGmZwMDDM",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 2,
    ["name"] = "Drdmg-tichondrius",
    ["code"] = "CsPASnrjTdwaLTX9NnLQoJJXfMDYmBjZmZYWmZmZYbmZwMmZmxMjhxMDmZmZmBAAAAAAAAAgNzmhBGY2YwwmxMDzMgBwAwMDDM",
    ["classId"] = 6,
    ["specId"] = 251,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 1,
    ["name"] = "Ðeathbyaqt-dragonmaw",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBjZGDzyYmZa2mZGjhZAAAAAAAAMzwMDAWmxYMzMmxMGsNzmZMLaGY2Y2mGLMAzAwYmZMDmZmZGzMG",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 2,
    ["name"] = "Omk-moon-guard",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmZ4BMDjZWGzMTz2MGzMMDAAAAAAAgZGmZAwyMGjZmxMmxgtZ2MzMLamlNmNmtpxCDwMAMmZGzgZmZmxMjB",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 3,
    ["name"] = "Bigbadbeezyy-balnazzar",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmZYMDjZWGzMTz2MGjhZAAAAAAAAMzwMDAWmxYYmZmxMGsNzmZMLaGY2Y2mGLMAzAwYmZMDmZmZGzMG",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 4,
    ["name"] = "Üuü-barthilas",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBjZGDzyYmZa2mxYmhZAAAAAAAAMDmZAwyMmZYmxMzMGsNzmZMLaGY2Y2mGLMAzAw8AzMjZwMzMzYmxA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "shuffle_deathknight_unholy",
    ["rank"] = 5,
    ["name"] = "Pwaff-illidan",
    ["code"] = "CwPASnrjTdwaLTX9NnLQoJJXfAYmBjZMYWGzMTz2MzYmZMDAAAAAAAgZeAmZAwyMmZMzMmxMGsNzmZmZRzstxsxsNNWYAmBgxMzYGgZmhZMA",
    ["classId"] = 6,
    ["specId"] = 252,
  },
  {
    ["bracket"] = "shuffle_druid_restoration",
    ["rank"] = 1,
    ["name"] = "Moxie-moon-guard",
    ["code"] = "CgGA8cL7tpvige+kkmGM9zUPWDAAAAAAAAAAAgZmxsMMjZWMLzDMzMWGY2MMaimZmlxMzMLjZGAAAAAADLzAW2mZwYWGATNzysMzMDAgFjZeAgFGMYsgBYmZmFYA",
    ["classId"] = 11,
    ["specId"] = 104,
  },
  {
    ["bracket"] = "shuffle_druid_restoration",
    ["rank"] = 1,
    ["name"] = "Vohmfg-tichondrius",
    ["code"] = "CkGA8cL7tpvige+kkmGM9zUPWPMzMbMjxMzsNmhxsxsYbGAAAAAAAAAAsMDNbmx0MzMwsZmZmZxAAAAAAMgBwA22GLYamZZAAMbjlmFDLwMzgxCoZAwMzMDAD",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "shuffle_druid_restoration",
    ["rank"] = 2,
    ["name"] = "Wendalax-sargeras",
    ["code"] = "CkGA8cL7tpvige+kkmGM9zUPWPMmZjZMzMzsMmZMmNmFmBAAAAAAAAAALzQzmZMNzMDMbmZmZ2MYAAAAAYAAMgtFgJzsMAAmtZWa2mZxGjZegBjFQzAgZmZGAGA",
    ["classId"] = 11,
    ["specId"] = 105,
  },
  {
    ["bracket"] = "shuffle_shaman_elemental",
    ["rank"] = 1,
    ["name"] = "Jerkdaddy-aggramar",
    ["code"] = "CYQARUG2fGwHkLP0T7/MoTNl/AAAAAzMLbzMGjZZZjxMMDAAAAYxMbbmZG2MswsNz0QzsAAMzYMz2ipFzMjxixMjZmtZzMLDmxsMAwMjBwMjhZMA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "shuffle_shaman_elemental",
    ["rank"] = 2,
    ["name"] = "Meatbeaterx-aggramar",
    ["code"] = "CYQARUG2fGwHkLP0T7/MoTNl/AAAAAzMLbzMGjZZZjxMMDAAAAYxMbbmZG2MswsNz0QzsAAMzMjZ2WMtMmZMWMmZMzsNbMLDmxsMAwMjBwMjhZMA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "shuffle_shaman_elemental",
    ["rank"] = 3,
    ["name"] = "Ttvozzyxy-tichondrius",
    ["code"] = "CYQARUG2fGwHkLP0T7/MoTNl/AAAAAzMLbzMGMLbbGzMmZAAAAALmZZxMzwmhFmlZmGamNAY2mZMGbLmWYGGLmZmxMzmNjlZMjZWAAzMGYmZmxwwA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "shuffle_shaman_elemental",
    ["rank"] = 4,
    ["name"] = "Bøøgaa-proudmoore",
    ["code"] = "CYQARUG2fGwHkLP0T7/MoTNl/AAAAAzMLbzMGjZZZhZmhZAAAAALmZZzMzwmhFmtZmGamNAYWGzMGbLmWYGGLzMzMmZ2sZmlhxYWAAzMAzMzMGmxA",
    ["classId"] = 7,
    ["specId"] = 262,
  },
  {
    ["bracket"] = "shuffle_shaman_elemental",
    ["rank"] = 1,
    ["name"] = "Quiggys-malganis",
    ["code"] = "CcQARUG2fGwHkLP0T7/MoTNl/MzMjZGPwMzMzMzMzYGAAAAAAAAAYBbLGzMbLasNMDzMNYDgZbwYstMjFmZ2GLmZmhZ2GzAAYYGzYmJmZMDGM+AA",
    ["classId"] = 7,
    ["specId"] = 263,
  },
  {
    ["bracket"] = "shuffle_mage_arcane",
    ["rank"] = 1,
    ["name"] = "Jüker-stormrage",
    ["code"] = "C4DAMhlVtghLZL4RZzExaQoBYNmtlZWmZmZzyDMzQzwAAAwAAgAmZmZZZmJWAAYZMzMjxilZmZMzMjxMzMjFmZGmBAYAAAMzCAMGA8BM",
    ["classId"] = 8,
    ["specId"] = 62,
  },
  {
    ["bracket"] = "shuffle_mage_arcane",
    ["rank"] = 2,
    ["name"] = "Zetoss-proudmoore",
    ["code"] = "C4DAMhlVtghLZL4RZzExaQoBYZGGLzMzswMzQzMzMAAAGAwMz0stsMzMzMLLzMxCAAGmZGz2ilZmZMzYMmZmZsxMzMmBAYAAAMzCmZAzAghB",
    ["classId"] = 8,
    ["specId"] = 62,
  },
};
